/* -*- Mode: C++ -*- */

/*============================================================================
 * File: dwdstAlphabetCompiler.h
 * Author:  Bryan Jurish <moocow@ling.uni-potsdam.de>
 * Description:
 *    Compiler for TnT alphabet files for DWDS disambiguator
 *============================================================================*/

#ifndef _DWDST_ALPHABET_COMPILER_H
#define _DWDST_ALPHABET_COMPILER_H

#include <stdio.h>
#include <stdarg.h>
#include <string.h>

#include <FSM.h>
#include <FSMSymSpec.h>

#include "dwdstTypes.h"
#include "dwdstAlphabetLexer.h"
#include "dwdstAlphabetParser.h"

/**
 * dwdstAlphabetCompiler compiles dwdst alphabetet files into
 * internal tables for dwdstDisambiguator, using a lexer/parser pair generated by
 * Alain Coetmeur's flex++ and bison++ programs.
 *
 * \brief Alphabet-file compiler.
 */
class dwdstAlphabetCompiler : public dwdstAlphabetParser {
 public:
  // -- public data

  /** flex++ lexer object */
  dwdstAlphabetLexer theLexer;

  /**
   * objname: name to use for object when reporting errors -- default: "dwdstAlphabetCompiler"
   * \b Warning: no copying is performed on this string; you must alloc&free it yourself!
   */
  char *objname;

  /**
   * srcname: name to use for current file when reporting errors -- default: "(unknown)"
   * \b Warning: no copying is performed on this string; you must alloc&free it yourself!
   */
  char *srcname;

 public:
  // -- public methods: CONSTRUCTORS / DESTRUCTORS
  /** Default constructor */
  dwdstAlphabetCompiler(FSMSymSpec *insyms=NULL,
			FSMSymSpec *outsyms=NULL,
			dwdstSymbolVector2SymbolMap *vectors2symbols=NULL)
    : objname(NULL), srcname(NULL)
  {
    isyms = insyms;
    osyms = outsyms;
    vec2sym = vectors2symbols;
    if (!recomp) {
      recomp = new FSMRegexCompiler();
    }
  };

  /** Default destructor */
  virtual ~dwdstAlphabetCompiler(void)
  {
    vectors.clear();
    if (recomp) {
      delete recomp;
      recomp = NULL;
    }
  };


  // -- high-level parsing methods

  /** parse an alphabetet from a C-stream.  Returns NULL on error. */
  inline dwdstSymbolVector2SymbolMap *parse_from_file(FILE *file, const char *filename=NULL) {
      select_streams(file,stdout);
      return parse_alphabet();
  };

  /** parse one regular expression from a C-string.  Returns NULL on error. */
  inline dwdstSymbolVector2SymbolMap *parse_from_string(const char *string, const char *srcname=NULL) {
    select_string(string,srcname);
    return parse_alphabet();
  };

  // -- low-level public methods: INPUT SELECTION
  /** low-level input selection: input from a C-stream. */
  void select_streams(FILE *in, FILE *out, const char *my_srcname=NULL) {
    theLexer.select_streams(in,out);
    srcname = (char *)my_srcname;
  };

  /**
   * low-level input selection: input from a C-string.
   * \b WARNING: do NOT free the string 'in' until parsing has finished!
   */
  void select_string(const char *in, const char *my_srcname=NULL) {
    theLexer.select_string(in);
    srcname = (char *)my_srcname;
  };

  // -- low-level public methods: PARSING
  virtual int yylex();

  /**
   * low-level parsing method: parse all remaining n-grams
   * from the currently selected input source.
   */
  inline dwdstSymbolVector2SymbolMap *parse_alphabet();

  // -- low-level public methods: ERRORS & WARNINGS
  /** yyerror: report parse errors. */
  virtual void yyerror(const char *msg);

  /** yywarn: report parse warnings. */
  virtual void yywarn(const char *msg);

  /** yycarp: report anything */
  virtual void yycarp(char *fmt, ...);

  /** do actual parsing for for an alphabet-line */
  virtual void compile_alphabet_class(FSMSymbolString *shortName,
				      FSMSymbolString *longName,
				      FSMSymbolString *regex);

  /** debugging */
  void dump_symbol_vector(const char *label,
			  const char *name,
			  const FSMSymbol class_symbol,
			  const FSM::FSMSymbolVector v);
};


#endif /* _DWDST_ALPHABET_COMPILER_H */
