---
abstract: 'install the libgfsm C library on your system'
author:
  - 'Bryan Jurish <moocow@cpan.org>'
build_requires: {}
configure_requires:
  Alien::Base: '0.001'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Gfsm
provides:
  Alien::Gfsm:
    file: lib/Alien/Gfsm.pm
    version: '0.001'
requires:
  Alien::Base: '0.005'
  File::ShareDir: '1.00'
  perl: v5.8.9
resources:
  license: http://dev.perl.org/licenses/
version: '0.001'
