/* Generated by re2c 0.13.5 on Mon Jul  7 15:01:43 2014 */
#include "wasteAnnotator.h"

/*-- moo: useful shortcuts for re2c actions --*/
#define annot0(a)		token.insert(a,"[" a "]")
#define annot1(a1) 		annot0(a1); return
#define annot2(a1,a2)		annot0(a1); annot0(a2); return
#define annot3(a1,a2,a3)	annot0(a1); annot0(a2); annot0(a3); return
#define annot4(a1,a2,a3,a4)	annot0(a1); annot0(a2); annot0(a3); annot0(a4); return

namespace moot {

  void wasteAnnotator::annotate_token(mootToken& token)
  {
    const unsigned char *sp  = (const unsigned char*)token.tok_text.c_str();
    const unsigned char *m   = sp;

    

    //-- Auto-generated property rules go here
    

    //-- Manual definitions
    

    
            {
              unsigned char yych;
              unsigned int yyaccept = 0;

              yych = *sp;
              if (yych <= 'k') {
                if (yych <= '?') {
                  if (yych <= '*') {
                    if (yych <= '#') {
                      if (yych <= 0x00) goto yy42;
                      if (yych <= ' ') goto yy39;
                      if (yych <= '!') goto yy5;
                      goto yy17;
                    } else {
                      if (yych <= '%') {
                        if (yych <= '$') goto yy10;
                        goto yy8;
                      } else {
                        if (yych == '\'') goto yy18;
                        goto yy17;
                      }
                    }
                  } else {
                    if (yych <= '/') {
                      if (yych <= ',') {
                        if (yych <= '+') goto yy19;
                        goto yy6;
                      } else {
                        if (yych <= '-') goto yy20;
                        if (yych >= '/') goto yy17;
                      }
                    } else {
                      if (yych <= ':') {
                        if (yych <= '9') goto yy37;
                        goto yy4;
                      } else {
                        if (yych <= ';') goto yy7;
                        if (yych <= '>') goto yy17;
                        goto yy5;
                      }
                    }
                  }
                } else {
                  if (yych <= 'V') {
                    if (yych <= 'H') {
                      if (yych <= '@') goto yy17;
                      if (yych <= 'B') goto yy40;
                      if (yych <= 'D') goto yy38;
                      goto yy40;
                    } else {
                      if (yych <= 'K') {
                        if (yych <= 'J') goto yy38;
                        goto yy40;
                      } else {
                        if (yych <= 'M') goto yy38;
                        if (yych <= 'U') goto yy40;
                        goto yy38;
                      }
                    }
                  } else {
                    if (yych <= '`') {
                      if (yych <= 'X') {
                        if (yych <= 'W') goto yy40;
                        goto yy38;
                      } else {
                        if (yych <= 'Z') goto yy40;
                        if (yych <= '_') goto yy17;
                        goto yy21;
                      }
                    } else {
                      if (yych <= 'd') {
                        if (yych <= 'b') goto yy40;
                        goto yy38;
                      } else {
                        if (yych <= 'h') goto yy40;
                        if (yych <= 'j') goto yy38;
                        goto yy40;
                      }
                    }
                  }
                }
              } else {
                if (yych <= 0xD4) {
                  if (yych <= 0xC2) {
                    if (yych <= 'w') {
                      if (yych <= 'm') goto yy38;
                      if (yych <= 'u') goto yy40;
                      if (yych <= 'v') goto yy38;
                      goto yy41;
                    } else {
                      if (yych <= 'z') {
                        if (yych <= 'x') goto yy38;
                        goto yy40;
                      } else {
                        if (yych <= '~') goto yy17;
                        if (yych <= 0xC1) goto yy39;
                        goto yy9;
                      }
                    }
                  } else {
                    if (yych <= 0xCD) {
                      if (yych <= 0xCA) {
                        if (yych <= 0xC3) goto yy33;
                        goto yy39;
                      } else {
                        if (yych <= 0xCB) goto yy32;
                        if (yych <= 0xCC) goto yy39;
                        goto yy24;
                      }
                    } else {
                      if (yych <= 0xCF) {
                        if (yych <= 0xCE) goto yy25;
                        goto yy34;
                      } else {
                        if (yych == 0xD2) goto yy35;
                        goto yy39;
                      }
                    }
                  }
                } else {
                  if (yych <= 0xDF) {
                    if (yych <= 0xD9) {
                      if (yych <= 0xD6) {
                        if (yych <= 0xD5) goto yy26;
                        goto yy22;
                      } else {
                        if (yych <= 0xD7) goto yy27;
                        if (yych <= 0xD8) goto yy11;
                        goto yy28;
                      }
                    } else {
                      if (yych <= 0xDB) {
                        if (yych <= 0xDA) goto yy39;
                        goto yy29;
                      } else {
                        if (yych <= 0xDC) goto yy30;
                        if (yych <= 0xDE) goto yy39;
                        goto yy31;
                      }
                    }
                  } else {
                    if (yych <= 0xE4) {
                      if (yych <= 0xE1) {
                        if (yych <= 0xE0) goto yy13;
                        goto yy12;
                      } else {
                        if (yych <= 0xE2) goto yy14;
                        if (yych <= 0xE3) goto yy23;
                        goto yy36;
                      }
                    } else {
                      if (yych <= 0xEA) {
                        if (yych <= 0xE9) goto yy39;
                        goto yy16;
                      } else {
                        if (yych == 0xEF) goto yy15;
                        goto yy39;
                      }
                    }
                  }
                }
              }
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '.') {
                if (yych <= 0x00) goto yy248;
                if (yych <= '-') goto yy57;
                goto yy240;
              } else {
                if (yych == ':') goto yy242;
                goto yy57;
              }
yy3:
              { return; }
yy4:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '.') {
                if (yych <= 0x00) goto yy244;
                if (yych <= '-') goto yy57;
                goto yy240;
              } else {
                if (yych == ':') goto yy242;
                goto yy57;
              }
yy5:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '!') {
                if (yych <= 0x00) goto yy237;
                if (yych <= ' ') goto yy57;
                goto yy235;
              } else {
                if (yych == '?') goto yy235;
                goto yy57;
              }
yy6:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy233;
              goto yy57;
yy7:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy231;
              goto yy57;
yy8:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy229;
              goto yy57;
yy9:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xAD) {
                if (yych <= 0xA6) {
                  if (yych <= 0xA0) {
                    if (yych <= 0x00) goto yy3;
                    goto yy57;
                  } else {
                    if (yych <= 0xA1) goto yy84;
                    if (yych <= 0xA5) goto yy124;
                    goto yy84;
                  }
                } else {
                  if (yych <= 0xA9) {
                    if (yych <= 0xA7) goto yy226;
                    goto yy84;
                  } else {
                    if (yych <= 0xAA) goto yy57;
                    if (yych <= 0xAB) goto yy84;
                    goto yy188;
                  }
                }
              } else {
                if (yych <= 0xB8) {
                  if (yych <= 0xB3) {
                    if (yych <= 0xB1) goto yy84;
                    goto yy57;
                  } else {
                    if (yych == 0xB5) goto yy57;
                    goto yy84;
                  }
                } else {
                  if (yych <= 0xBB) {
                    if (yych <= 0xBA) goto yy57;
                    goto yy84;
                  } else {
                    if (yych == 0xBF) goto yy84;
                    goto yy57;
                  }
                }
              }
yy10:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy125;
              goto yy57;
yy11:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x8F) {
                if (yych <= 0x85) {
                  if (yych <= 0x00) goto yy3;
                  goto yy57;
                } else {
                  if (yych == 0x8B) goto yy124;
                  goto yy84;
                }
              } else {
                if (yych <= 0x9B) {
                  if (yych <= 0x9A) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0x9D) goto yy57;
                  if (yych <= 0x9F) goto yy84;
                  goto yy57;
                }
              }
yy12:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA0) {
                if (yych <= 0x8F) {
                  if (yych <= 0x82) {
                    if (yych <= 0x00) goto yy3;
                    if (yych <= 0x80) goto yy57;
                    if (yych <= 0x81) goto yy204;
                    goto yy205;
                  } else {
                    if (yych <= 0x8C) {
                      if (yych <= 0x83) goto yy206;
                      goto yy57;
                    } else {
                      if (yych <= 0x8D) goto yy207;
                      if (yych <= 0x8E) goto yy208;
                      goto yy57;
                    }
                  }
                } else {
                  if (yych <= 0x9A) {
                    if (yych <= 0x90) goto yy209;
                    if (yych <= 0x98) goto yy57;
                    if (yych <= 0x99) goto yy210;
                    goto yy211;
                  } else {
                    if (yych <= 0x9C) {
                      if (yych <= 0x9B) goto yy212;
                      goto yy213;
                    } else {
                      if (yych <= 0x9E) goto yy57;
                      if (yych <= 0x9F) goto yy214;
                      goto yy215;
                    }
                  }
                }
              } else {
                if (yych <= 0xAD) {
                  if (yych <= 0xA7) {
                    if (yych == 0xA5) goto yy216;
                    if (yych <= 0xA6) goto yy57;
                    goto yy217;
                  } else {
                    if (yych <= 0xA9) {
                      if (yych <= 0xA8) goto yy218;
                      goto yy57;
                    } else {
                      if (yych <= 0xAA) goto yy219;
                      if (yych <= 0xAC) goto yy57;
                      goto yy220;
                    }
                  }
                } else {
                  if (yych <= 0xB2) {
                    if (yych <= 0xAF) goto yy57;
                    if (yych <= 0xB0) goto yy221;
                    if (yych <= 0xB1) goto yy222;
                    goto yy57;
                  } else {
                    if (yych <= 0xBD) {
                      if (yych <= 0xB3) goto yy223;
                      goto yy57;
                    } else {
                      if (yych <= 0xBE) goto yy224;
                      if (yych <= 0xBF) goto yy225;
                      goto yy57;
                    }
                  }
                }
              }
yy13:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB0) {
                if (yych <= 0xA7) {
                  if (yych <= 0xA0) {
                    if (yych <= 0x00) goto yy3;
                    if (yych <= 0x9F) goto yy57;
                    goto yy189;
                  } else {
                    if (yych == 0xA5) goto yy190;
                    if (yych <= 0xA6) goto yy57;
                    goto yy191;
                  }
                } else {
                  if (yych <= 0xAC) {
                    if (yych == 0xAB) goto yy192;
                    goto yy57;
                  } else {
                    if (yych <= 0xAD) goto yy193;
                    if (yych == 0xAF) goto yy194;
                    goto yy57;
                  }
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych <= 0xB3) {
                    if (yych <= 0xB1) goto yy195;
                    if (yych <= 0xB2) goto yy57;
                    goto yy196;
                  } else {
                    if (yych == 0xB5) goto yy197;
                    if (yych <= 0xB6) goto yy57;
                    goto yy198;
                  }
                } else {
                  if (yych <= 0xBC) {
                    if (yych <= 0xB8) goto yy199;
                    if (yych <= 0xB9) goto yy200;
                    if (yych <= 0xBB) goto yy57;
                    goto yy201;
                  } else {
                    if (yych <= 0xBD) goto yy57;
                    if (yych <= 0xBE) goto yy202;
                    if (yych <= 0xBF) goto yy203;
                    goto yy57;
                  }
                }
              }
yy14:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x9B) {
                if (yych <= 0x8C) {
                  if (yych <= 0x84) {
                    if (yych <= 0x80) {
                      if (yych <= 0x00) goto yy3;
                      if (yych <= 0x7F) goto yy57;
                      goto yy135;
                    } else {
                      if (yych <= 0x81) goto yy137;
                      if (yych <= 0x82) goto yy138;
                      if (yych <= 0x83) goto yy57;
                      goto yy139;
                    }
                  } else {
                    if (yych <= 0x88) {
                      if (yych <= 0x85) goto yy140;
                      if (yych <= 0x86) goto yy141;
                      if (yych <= 0x87) goto yy142;
                      goto yy143;
                    } else {
                      if (yych <= 0x89) goto yy144;
                      if (yych <= 0x8A) goto yy145;
                      if (yych <= 0x8B) goto yy146;
                      goto yy147;
                    }
                  }
                } else {
                  if (yych <= 0x93) {
                    if (yych <= 0x8F) {
                      if (yych <= 0x8D) goto yy148;
                      if (yych <= 0x8E) goto yy149;
                      goto yy150;
                    } else {
                      if (yych <= 0x90) goto yy151;
                      if (yych <= 0x91) goto yy152;
                      if (yych <= 0x92) goto yy153;
                      goto yy154;
                    }
                  } else {
                    if (yych <= 0x97) {
                      if (yych <= 0x94) goto yy155;
                      if (yych <= 0x95) goto yy156;
                      if (yych <= 0x96) goto yy157;
                      goto yy158;
                    } else {
                      if (yych <= 0x98) goto yy159;
                      if (yych <= 0x99) goto yy160;
                      if (yych <= 0x9A) goto yy161;
                      goto yy162;
                    }
                  }
                }
              } else {
                if (yych <= 0xAA) {
                  if (yych <= 0xA2) {
                    if (yych <= 0x9E) {
                      if (yych <= 0x9C) goto yy163;
                      if (yych <= 0x9D) goto yy164;
                      goto yy165;
                    } else {
                      if (yych <= 0x9F) goto yy166;
                      if (yych <= 0xA0) goto yy167;
                      if (yych <= 0xA1) goto yy168;
                      goto yy169;
                    }
                  } else {
                    if (yych <= 0xA6) {
                      if (yych <= 0xA3) goto yy170;
                      if (yych <= 0xA4) goto yy171;
                      if (yych <= 0xA5) goto yy172;
                      goto yy173;
                    } else {
                      if (yych <= 0xA7) goto yy174;
                      if (yych <= 0xA8) goto yy175;
                      if (yych <= 0xA9) goto yy176;
                      goto yy177;
                    }
                  }
                } else {
                  if (yych <= 0xB8) {
                    if (yych <= 0xAD) {
                      if (yych <= 0xAB) goto yy178;
                      if (yych <= 0xAC) goto yy179;
                      goto yy180;
                    } else {
                      if (yych == 0xB3) goto yy181;
                      if (yych <= 0xB7) goto yy57;
                      goto yy136;
                    }
                  } else {
                    if (yych <= 0xBC) {
                      if (yych <= 0xB9) goto yy57;
                      if (yych <= 0xBA) goto yy182;
                      if (yych <= 0xBB) goto yy183;
                      goto yy184;
                    } else {
                      if (yych <= 0xBD) goto yy185;
                      if (yych <= 0xBE) goto yy186;
                      if (yych <= 0xBF) goto yy187;
                      goto yy57;
                    }
                  }
                }
              }
yy15:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB7) {
                if (yych <= 0xAC) {
                  if (yych <= 0x00) goto yy3;
                  if (yych <= 0xAB) goto yy57;
                  goto yy127;
                } else {
                  if (yych == 0xB4) goto yy128;
                  if (yych <= 0xB6) goto yy57;
                  goto yy129;
                }
              } else {
                if (yych <= 0xBC) {
                  if (yych <= 0xB8) goto yy130;
                  if (yych <= 0xB9) goto yy131;
                  if (yych <= 0xBB) goto yy57;
                  goto yy132;
                } else {
                  if (yych <= 0xBD) goto yy133;
                  if (yych == 0xBF) goto yy134;
                  goto yy57;
                }
              }
yy16:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA0) {
                if (yych <= 0x99) {
                  if (yych <= 0x92) {
                    if (yych <= 0x00) goto yy3;
                    if (yych <= 0x91) goto yy57;
                    goto yy108;
                  } else {
                    if (yych <= 0x93) goto yy109;
                    if (yych <= 0x97) goto yy57;
                    if (yych <= 0x98) goto yy110;
                    goto yy111;
                  }
                } else {
                  if (yych <= 0x9C) {
                    if (yych <= 0x9A) goto yy57;
                    if (yych <= 0x9B) goto yy112;
                    goto yy113;
                  } else {
                    if (yych == 0x9E) goto yy114;
                    if (yych <= 0x9F) goto yy57;
                    goto yy115;
                  }
                }
              } else {
                if (yych <= 0xA7) {
                  if (yych <= 0xA3) {
                    if (yych <= 0xA1) goto yy116;
                    if (yych <= 0xA2) goto yy57;
                    goto yy117;
                  } else {
                    if (yych <= 0xA4) goto yy118;
                    if (yych <= 0xA5) goto yy119;
                    if (yych <= 0xA6) goto yy57;
                    goto yy120;
                  }
                } else {
                  if (yych <= 0xAA) {
                    if (yych == 0xA9) goto yy121;
                    goto yy57;
                  } else {
                    if (yych <= 0xAB) goto yy122;
                    if (yych == 0xAF) goto yy123;
                    goto yy57;
                  }
                }
              }
yy17:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy85;
              goto yy57;
yy18:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy85;
              if (yych == '\'') goto yy84;
              goto yy57;
yy19:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy85;
              if (yych <= '/') goto yy57;
              if (yych <= '9') goto yy75;
              goto yy57;
yy20:
              yych = *++sp;
              if (yych <= '/') {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy100;
                  goto yy105;
                } else {
                  if (yych <= '-') goto yy101;
                  if (yych <= '.') goto yy106;
                  goto yy105;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= '9') goto yy107;
                  if (yych <= 0xC1) goto yy105;
                  goto yy103;
                } else {
                  if (yych == 0xE2) goto yy104;
                  goto yy105;
                }
              }
yy21:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy85;
              if (yych == '`') goto yy84;
              goto yy57;
yy22:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x8A) {
                if (yych <= 0x00) goto yy3;
                if (yych <= 0x88) goto yy57;
                goto yy84;
              } else {
                if (yych == 0xBE) goto yy84;
                goto yy57;
              }
yy23:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x87) {
                if (yych <= 0x81) {
                  if (yych <= 0x00) goto yy3;
                  if (yych == 0x80) goto yy87;
                  goto yy57;
                } else {
                  if (yych <= 0x83) {
                    if (yych <= 0x82) goto yy88;
                    goto yy89;
                  } else {
                    if (yych <= 0x85) goto yy57;
                    if (yych <= 0x86) goto yy90;
                    goto yy91;
                  }
                }
              } else {
                if (yych <= 0x8B) {
                  if (yych <= 0x88) goto yy92;
                  if (yych <= 0x89) goto yy93;
                  if (yych <= 0x8A) goto yy94;
                  goto yy95;
                } else {
                  if (yych <= 0x8D) {
                    if (yych <= 0x8C) goto yy96;
                    goto yy97;
                  } else {
                    if (yych <= 0x8E) goto yy98;
                    if (yych <= 0x8F) goto yy99;
                    goto yy57;
                  }
                }
              }
yy24:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB5) {
                if (yych <= 0x00) goto yy3;
                if (yych <= 0xB4) goto yy57;
                goto yy84;
              } else {
                if (yych == 0xBE) goto yy84;
                goto yy57;
              }
yy25:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x85) {
                if (yych <= 0x00) goto yy3;
                if (yych <= 0x83) goto yy57;
                goto yy84;
              } else {
                if (yych == 0x87) goto yy84;
                goto yy57;
              }
yy26:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych <= 0x99) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy27:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x83) {
                if (yych <= 0x7F) {
                  if (yych <= 0x00) goto yy3;
                  goto yy57;
                } else {
                  if (yych <= 0x80) goto yy84;
                  if (yych <= 0x82) goto yy57;
                  goto yy84;
                }
              } else {
                if (yych <= 0x86) {
                  if (yych <= 0x85) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xB2) goto yy57;
                  if (yych <= 0xB4) goto yy84;
                  goto yy57;
                }
              }
yy28:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych <= 0xA9) goto yy57;
              if (yych <= 0xAD) goto yy84;
              goto yy57;
yy29:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA8) {
                if (yych <= 0x00) goto yy3;
                if (yych == 0x94) goto yy84;
                goto yy57;
              } else {
                if (yych <= 0xA9) goto yy84;
                if (yych <= 0xBC) goto yy57;
                if (yych <= 0xBE) goto yy84;
                goto yy57;
              }
yy30:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x8D) goto yy84;
              goto yy57;
yy31:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych <= 0xB5) goto yy57;
              if (yych <= 0xB9) goto yy84;
              goto yy57;
yy32:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA4) {
                if (yych <= 0x85) {
                  if (yych <= 0x00) goto yy3;
                  if (yych <= 0x81) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0x91) goto yy57;
                  if (yych <= 0x9F) goto yy84;
                  goto yy57;
                }
              } else {
                if (yych <= 0xAD) {
                  if (yych == 0xAC) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xAE) goto yy57;
                  if (yych <= 0xBF) goto yy84;
                  goto yy57;
                }
              }
yy33:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x97) {
                if (yych <= 0x00) goto yy3;
                if (yych <= 0x96) goto yy57;
                goto yy84;
              } else {
                if (yych == 0xB7) goto yy84;
                goto yy57;
              }
yy34:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych == 0xB6) goto yy84;
              goto yy57;
yy35:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych == 0x82) goto yy84;
              goto yy57;
yy36:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              if (yych == 0xB7) goto yy83;
              goto yy57;
yy37:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy77;
                  if (yych <= 0x1F) goto yy57;
                  goto yy73;
                } else {
                  if (yych == ',') goto yy73;
                  goto yy57;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy74;
                  if (yych <= '/') goto yy57;
                  goto yy75;
                } else {
                  if (yych <= ':') goto yy73;
                  if (yych == '_') goto yy73;
                  goto yy57;
                }
              }
yy38:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 'V') {
                if (yych <= '@') {
                  if (yych <= '.') {
                    if (yych <= 0x00) goto yy3;
                    if (yych <= '-') goto yy57;
                    goto yy70;
                  } else {
                    if (yych == ':') goto yy45;
                    if (yych <= '?') goto yy57;
                    goto yy43;
                  }
                } else {
                  if (yych <= 'J') {
                    if (yych <= 'B') goto yy47;
                    if (yych <= 'D') goto yy68;
                    if (yych <= 'H') goto yy47;
                    goto yy68;
                  } else {
                    if (yych <= 'K') goto yy47;
                    if (yych <= 'M') goto yy68;
                    if (yych <= 'U') goto yy47;
                    goto yy68;
                  }
                }
              } else {
                if (yych <= 'j') {
                  if (yych <= '`') {
                    if (yych == 'X') goto yy68;
                    if (yych <= 'Z') goto yy47;
                    goto yy57;
                  } else {
                    if (yych <= 'b') goto yy47;
                    if (yych <= 'd') goto yy68;
                    if (yych <= 'h') goto yy47;
                    goto yy68;
                  }
                } else {
                  if (yych <= 'v') {
                    if (yych <= 'k') goto yy47;
                    if (yych <= 'm') goto yy68;
                    if (yych <= 'u') goto yy47;
                    goto yy68;
                  } else {
                    if (yych == 'x') goto yy68;
                    if (yych <= 'z') goto yy47;
                    goto yy57;
                  }
                }
              }
yy39:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy3;
              goto yy57;
yy40:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '?') {
                if (yych <= 0x00) goto yy3;
                if (yych == ':') goto yy45;
                goto yy57;
              } else {
                if (yych <= 'Z') {
                  if (yych <= '@') goto yy43;
                  goto yy47;
                } else {
                  if (yych <= '`') goto yy57;
                  if (yych <= 'z') goto yy47;
                  goto yy57;
                }
              }
yy41:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '@') {
                if (yych <= '9') {
                  if (yych <= 0x00) goto yy3;
                  goto yy57;
                } else {
                  if (yych <= ':') goto yy45;
                  if (yych <= '?') goto yy57;
                  goto yy43;
                }
              } else {
                if (yych <= 'v') {
                  if (yych <= 'Z') goto yy47;
                  if (yych <= '`') goto yy57;
                  goto yy47;
                } else {
                  if (yych <= 'w') goto yy49;
                  if (yych <= 'z') goto yy47;
                  goto yy57;
                }
              }
yy42:
              yych = *++sp;
              goto yy3;
yy43:
              yyaccept = 1;
              yych = *(m = ++sp);
              if (yych >= 0x01) goto yy57;
yy44:
              { annot4("NN","NE","XY","$LINK"); }
yy45:
              yych = *++sp;
              if (yych == '/') goto yy43;
              goto yy57;
yy46:
              sp = m;
              if (yyaccept <= 1) {
                if (yyaccept <= 0) {
                  goto yy3;
                } else {
                  goto yy44;
                }
              } else {
                goto yy102;
              }
yy47:
              ++sp;
              yych = *sp;
              if (yych <= '@') {
                if (yych <= '.') {
                  if (yych <= 0x00) goto yy46;
                  if (yych <= ',') goto yy56;
                  if (yych <= '-') goto yy50;
                  goto yy58;
                } else {
                  if (yych == ':') goto yy45;
                  if (yych <= '?') goto yy56;
                  goto yy43;
                }
              } else {
                if (yych <= 0xC1) {
                  if (yych <= 'Z') goto yy47;
                  if (yych <= '`') goto yy56;
                  if (yych <= 'z') goto yy47;
                  goto yy56;
                } else {
                  if (yych <= 0xC2) goto yy52;
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy49:
              yych = *++sp;
              if (yych <= 'Z') {
                if (yych <= ':') {
                  if (yych <= '9') goto yy57;
                  goto yy45;
                } else {
                  if (yych <= '?') goto yy57;
                  if (yych <= '@') goto yy43;
                  goto yy47;
                }
              } else {
                if (yych <= 'v') {
                  if (yych <= '`') goto yy57;
                  goto yy47;
                } else {
                  if (yych <= 'w') goto yy66;
                  if (yych <= 'z') goto yy47;
                  goto yy57;
                }
              }
yy50:
              ++sp;
              yych = *sp;
              if (yych <= '.') {
                if (yych <= 0x00) goto yy64;
                if (yych <= ',') goto yy56;
                if (yych <= '-') goto yy50;
                goto yy58;
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0xC1) goto yy56;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy52:
              ++sp;
              yych = *sp;
              if (yych <= 0xAB) {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy46;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy58;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0xAD) goto yy50;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych != 0xE2) goto yy56;
                }
              }
yy54:
              ++sp;
              yych = *sp;
              if (yych <= 0x80) {
                if (yych <= '-') {
                  if (yych <= 0x00) goto yy46;
                  if (yych >= '-') goto yy50;
                } else {
                  if (yych <= '.') goto yy58;
                  if (yych >= 0x80) goto yy62;
                }
              } else {
                if (yych <= 0xC1) {
                  if (yych == 0xB8) goto yy63;
                } else {
                  if (yych <= 0xC2) goto yy52;
                  if (yych == 0xE2) goto yy54;
                }
              }
yy56:
              ++sp;
              yych = *sp;
yy57:
              if (yych <= '.') {
                if (yych <= 0x00) goto yy46;
                if (yych <= ',') goto yy56;
                if (yych <= '-') goto yy50;
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy58:
              ++sp;
              yych = *sp;
              if (yych <= '.') {
                if (yych <= 0x00) goto yy60;
                if (yych <= ',') goto yy56;
                if (yych <= '-') goto yy50;
                goto yy58;
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy60:
              ++sp;
              { annot2("XY","$ABBREV"); }
yy62:
              ++sp;
              yych = *sp;
              if (yych <= 0x92) {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy46;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy58;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0x94) goto yy50;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy63:
              ++sp;
              yych = *sp;
              if (yych <= 0x96) {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy46;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy58;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0x97) goto yy50;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy64:
              ++sp;
              { annot1("TRUNC"); }
yy66:
              yych = *++sp;
              if (yych <= '?') {
                if (yych <= '.') {
                  if (yych <= '-') goto yy57;
                } else {
                  if (yych == ':') goto yy45;
                  goto yy57;
                }
              } else {
                if (yych <= 'Z') {
                  if (yych <= '@') goto yy43;
                  goto yy47;
                } else {
                  if (yych <= '`') goto yy57;
                  if (yych <= 'z') goto yy47;
                  goto yy57;
                }
              }
              yyaccept = 1;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy60;
              goto yy57;
yy68:
              ++sp;
              yych = *sp;
              if (yych <= 'X') {
                if (yych <= 'B') {
                  if (yych <= '.') {
                    if (yych <= 0x00) goto yy46;
                    if (yych <= ',') goto yy56;
                    if (yych <= '-') goto yy50;
                  } else {
                    if (yych <= ':') {
                      if (yych <= '9') goto yy56;
                      goto yy45;
                    } else {
                      if (yych <= '?') goto yy56;
                      if (yych <= '@') goto yy43;
                      goto yy47;
                    }
                  }
                } else {
                  if (yych <= 'K') {
                    if (yych <= 'D') goto yy68;
                    if (yych <= 'H') goto yy47;
                    if (yych <= 'J') goto yy68;
                    goto yy47;
                  } else {
                    if (yych <= 'U') {
                      if (yych <= 'M') goto yy68;
                      goto yy47;
                    } else {
                      if (yych == 'W') goto yy47;
                      goto yy68;
                    }
                  }
                }
              } else {
                if (yych <= 'u') {
                  if (yych <= 'd') {
                    if (yych <= 'Z') goto yy47;
                    if (yych <= '`') goto yy56;
                    if (yych <= 'b') goto yy47;
                    goto yy68;
                  } else {
                    if (yych <= 'j') {
                      if (yych <= 'h') goto yy47;
                      goto yy68;
                    } else {
                      if (yych <= 'k') goto yy47;
                      if (yych <= 'm') goto yy68;
                      goto yy47;
                    }
                  }
                } else {
                  if (yych <= 'z') {
                    if (yych == 'w') goto yy47;
                    if (yych <= 'x') goto yy68;
                    goto yy47;
                  } else {
                    if (yych <= 0xC2) {
                      if (yych <= 0xC1) goto yy56;
                      goto yy52;
                    } else {
                      if (yych == 0xE2) goto yy54;
                      goto yy56;
                    }
                  }
                }
              }
yy70:
              yych = *++sp;
              if (yych >= 0x01) goto yy57;
              ++sp;
              { annot3("ADJA","$ABBREV","$ORD"); }
yy73:
              ++sp;
              yych = *sp;
              if (yych <= '/') {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy46;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy58;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= '9') goto yy79;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy74:
              ++sp;
              yych = *sp;
              if (yych <= '/') {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy81;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy58;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= '9') goto yy79;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy75:
              ++sp;
              yych = *sp;
              if (yych <= '/') {
                if (yych <= '+') {
                  if (yych <= 0x00) goto yy77;
                  if (yych == ' ') goto yy73;
                  goto yy56;
                } else {
                  if (yych <= ',') goto yy73;
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy74;
                  goto yy56;
                }
              } else {
                if (yych <= '_') {
                  if (yych <= '9') goto yy75;
                  if (yych <= ':') goto yy73;
                  if (yych <= '^') goto yy56;
                  goto yy73;
                } else {
                  if (yych <= 0xC2) {
                    if (yych <= 0xC1) goto yy56;
                    goto yy52;
                  } else {
                    if (yych == 0xE2) goto yy54;
                    goto yy56;
                  }
                }
              }
yy77:
              ++sp;
              { annot1("CARD"); }
yy79:
              ++sp;
              yych = *sp;
              if (yych <= '/') {
                if (yych <= '+') {
                  if (yych <= 0x00) goto yy77;
                  if (yych == ' ') goto yy73;
                  goto yy56;
                } else {
                  if (yych <= ',') goto yy73;
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy74;
                  goto yy56;
                }
              } else {
                if (yych <= '_') {
                  if (yych <= '9') goto yy79;
                  if (yych <= ':') goto yy73;
                  if (yych <= '^') goto yy56;
                  goto yy73;
                } else {
                  if (yych <= 0xC2) {
                    if (yych <= 0xC1) goto yy56;
                    goto yy52;
                  } else {
                    if (yych == 0xE2) goto yy54;
                    goto yy56;
                  }
                }
              }
yy81:
              ++sp;
              { annot2("ADJA","$ORD"); }
yy83:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych >= 0xC0) goto yy57;
yy84:
              yych = *++sp;
              if (yych >= 0x01) goto yy57;
yy85:
              ++sp;
yy86:
              { annot1("$("); }
yy87:
              yych = *++sp;
              if (yych <= 0xAF) {
                if (yych <= 0x84) {
                  if (yych <= 0x80) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0x87) goto yy57;
                  if (yych <= 0xA0) goto yy84;
                  goto yy57;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych <= 0xB0) goto yy84;
                  if (yych <= 0xB5) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xBC) goto yy57;
                  if (yych <= 0xBF) goto yy84;
                  goto yy57;
                }
              }
yy88:
              yych = *++sp;
              if (yych <= 0x9A) goto yy57;
              if (yych <= 0x9C) goto yy84;
              if (yych == 0xA0) goto yy84;
              goto yy57;
yy89:
              yych = *++sp;
              if (yych == 0xBB) goto yy84;
              goto yy57;
yy90:
              yych = *++sp;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0x91) goto yy84;
              if (yych <= 0x95) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy91:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xA3) goto yy84;
              goto yy57;
yy92:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x9E) goto yy84;
              if (yych <= 0xA9) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy93:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x90) goto yy84;
              if (yych <= 0x9F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy94:
              yych = *++sp;
              if (yych <= 0x89) goto yy57;
              if (yych <= 0xB0) goto yy84;
              goto yy57;
yy95:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBE) goto yy84;
              goto yy57;
yy96:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy97:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy98:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy99:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy100:
              yych = *++sp;
              goto yy86;
yy101:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy64;
              goto yy57;
yy102:
              { annot1("TRUNC"); }
yy103:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy102;
              if (yych <= 0xAB) goto yy57;
              if (yych <= 0xAD) goto yy50;
              goto yy57;
yy104:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= 0x80) {
                if (yych <= 0x00) goto yy102;
                if (yych <= 0x7F) goto yy57;
                goto yy62;
              } else {
                if (yych == 0xB8) goto yy63;
                goto yy57;
              }
yy105:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy102;
              goto yy57;
yy106:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy60;
              goto yy57;
yy107:
              yyaccept = 2;
              yych = *(m = ++sp);
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy77;
                  if (yych <= 0x1F) goto yy57;
                  goto yy73;
                } else {
                  if (yych == ',') goto yy73;
                  goto yy57;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy74;
                  if (yych <= '/') goto yy57;
                  goto yy75;
                } else {
                  if (yych <= ':') goto yy73;
                  if (yych == '_') goto yy73;
                  goto yy57;
                }
              }
yy108:
              yych = *++sp;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy109:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x86) goto yy84;
              if (yych <= 0xBD) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy110:
              yych = *++sp;
              if (yych <= 0x8C) goto yy57;
              if (yych <= 0x8F) goto yy84;
              goto yy57;
yy111:
              yych = *++sp;
              if (yych == 0xB3) goto yy84;
              if (yych == 0xBE) goto yy84;
              goto yy57;
yy112:
              yych = *++sp;
              if (yych <= 0xB1) goto yy57;
              if (yych <= 0xB7) goto yy84;
              goto yy57;
yy113:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x96) goto yy84;
              if (yych <= 0x9F) goto yy57;
              if (yych <= 0xA1) goto yy84;
              goto yy57;
yy114:
              yych = *++sp;
              if (yych <= 0x88) goto yy57;
              if (yych <= 0x8A) goto yy84;
              goto yy57;
yy115:
              yych = *++sp;
              if (yych <= 0xB5) {
                if (yych <= 0xA7) goto yy57;
                if (yych <= 0xAB) goto yy84;
                goto yy57;
              } else {
                if (yych == 0xB8) goto yy124;
                if (yych <= 0xB9) goto yy84;
                goto yy57;
              }
yy116:
              yych = *++sp;
              if (yych <= 0xB3) goto yy57;
              if (yych <= 0xB7) goto yy84;
              goto yy57;
yy117:
              yych = *++sp;
              if (yych <= 0x8D) goto yy57;
              if (yych <= 0x8F) goto yy84;
              if (yych <= 0xB7) goto yy57;
              if (yych <= 0xBA) goto yy84;
              goto yy57;
yy118:
              yych = *++sp;
              if (yych <= 0xAD) goto yy57;
              if (yych <= 0xAF) goto yy84;
              goto yy57;
yy119:
              yych = *++sp;
              if (yych == 0x9F) goto yy84;
              goto yy57;
yy120:
              yych = *++sp;
              if (yych <= 0x80) goto yy57;
              if (yych <= 0x8D) goto yy84;
              if (yych <= 0x9D) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy121:
              yych = *++sp;
              if (yych <= 0x9B) goto yy57;
              if (yych <= 0x9F) goto yy84;
              if (yych <= 0xB6) goto yy57;
              if (yych <= 0xB9) goto yy84;
              goto yy57;
yy122:
              yych = *++sp;
              if (yych <= 0x9D) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy123:
              yych = *++sp;
              if (yych == 0xAB) goto yy84;
              goto yy57;
yy124:
              yych = *++sp;
              if (yych >= 0x01) goto yy57;
yy125:
              ++sp;
              { annot3("NN","$(","$CURRENCY"); }
yy127:
              yych = *++sp;
              if (yych == 0xA9) goto yy84;
              goto yy57;
yy128:
              yych = *++sp;
              if (yych <= 0xBD) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy129:
              yych = *++sp;
              if (yych <= 0xBB) goto yy57;
              if (yych <= 0xBC) goto yy124;
              if (yych <= 0xBD) goto yy84;
              goto yy57;
yy130:
              yych = *++sp;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0x99) goto yy84;
              if (yych <= 0xAF) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy131:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x7F) goto yy57;
                if (yych == 0x93) goto yy57;
                goto yy84;
              } else {
                if (yych <= 0xA8) {
                  if (yych <= 0xA7) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xA9) goto yy124;
                  if (yych <= 0xAB) goto yy84;
                  goto yy57;
                }
              }
yy132:
              yych = *++sp;
              if (yych <= 0x8F) {
                if (yych <= 0x80) goto yy57;
                if (yych == 0x84) goto yy124;
                goto yy84;
              } else {
                if (yych <= 0xA0) {
                  if (yych <= 0x99) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xBA) goto yy57;
                  if (yych <= 0xBF) goto yy84;
                  goto yy57;
                }
              }
yy133:
              yych = *++sp;
              if (yych == 0x80) goto yy84;
              if (yych <= 0x9A) goto yy57;
              if (yych <= 0xA5) goto yy84;
              goto yy57;
yy134:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x9F) goto yy57;
                if (yych <= 0xA1) goto yy124;
                if (yych <= 0xA4) goto yy84;
                goto yy124;
              } else {
                if (yych <= 0xAE) {
                  if (yych <= 0xA7) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xBB) goto yy57;
                  if (yych <= 0xBD) goto yy84;
                  goto yy57;
                }
              }
yy135:
              yych = *++sp;
              if (yych <= 0x94) {
                if (yych <= 0x8F) goto yy57;
                if (yych <= 0x92) goto yy84;
                goto yy188;
              } else {
                if (yych <= 0xA7) goto yy84;
                if (yych <= 0xAF) goto yy57;
                if (yych <= 0xBF) goto yy84;
                goto yy57;
              }
yy136:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych <= 0x7F) goto yy57;
                if (yych <= 0x96) goto yy84;
                goto yy188;
              } else {
                if (yych == 0xAF) goto yy57;
                if (yych <= 0xB1) goto yy84;
                goto yy57;
              }
yy137:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x9E) goto yy84;
              if (yych <= 0xB9) goto yy57;
              if (yych <= 0xBE) goto yy84;
              goto yy57;
yy138:
              yych = *++sp;
              if (yych <= 0x89) goto yy57;
              if (yych <= 0x8E) goto yy84;
              if (yych <= 0x9F) goto yy57;
              if (yych <= 0xB8) goto yy124;
              goto yy57;
yy139:
              yych = *++sp;
              switch (yych) {
              case 0x80:
              case 0x81:
              case 0x83:
              case 0x84:
              case 0x85:
              case 0x86:
              case 0x88:
              case 0x89:
              case 0x94:
              case 0x96:
              case 0x97:
              case 0x98:
              case 0x9E:
              case 0x9F:
              case 0xA0:
              case 0xA1:
              case 0xA2:
              case 0xA3:
              case 0xA5:
              case 0xA7:
              case 0xA9:
              case 0xAE:
              case 0xBA:
              case 0xBB:  goto yy84;
              default:  goto yy57;
              }
yy140:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x7F) goto yy57;
                if (yych <= 0x84) goto yy84;
                goto yy57;
              } else {
                if (yych == 0x8E) goto yy57;
                if (yych <= 0x8F) goto yy84;
                goto yy57;
              }
yy141:
              yych = *++sp;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy142:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy143:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy144:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy145:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy146:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy147:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy148:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy149:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy150:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xA8) goto yy84;
              goto yy57;
yy151:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xA6) goto yy84;
              goto yy57;
yy152:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x8A) goto yy84;
              goto yy57;
yy153:
              yych = *++sp;
              if (yych <= 0x9B) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy154:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xA9) goto yy84;
              goto yy57;
yy155:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy156:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy157:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy158:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy159:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy160:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy161:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy162:
              yych = *++sp;
              if (yych <= 0xA1) {
                if (yych <= 0x7F) goto yy57;
                if (yych == 0x8E) goto yy57;
                goto yy84;
              } else {
                if (yych <= 0xA3) {
                  if (yych <= 0xA2) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xA7) goto yy57;
                  if (yych <= 0xBF) goto yy84;
                  goto yy57;
                }
              }
yy163:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x80) goto yy57;
                if (yych == 0x85) goto yy57;
                goto yy84;
              } else {
                if (yych <= 0xA7) {
                  if (yych <= 0x8B) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xA8) goto yy57;
                  if (yych <= 0xBF) goto yy84;
                  goto yy57;
                }
              }
yy164:
              yych = *++sp;
              if (yych <= 0x8E) {
                if (yych <= 0x8B) {
                  if (yych <= 0x7F) goto yy57;
                  goto yy84;
                } else {
                  if (yych == 0x8D) goto yy84;
                  goto yy57;
                }
              } else {
                if (yych <= 0x9E) {
                  if (yych <= 0x92) goto yy84;
                  if (yych <= 0x95) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xA0) goto yy57;
                  if (yych <= 0xB5) goto yy84;
                  goto yy57;
                }
              }
yy165:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych == 0x94) goto yy84;
                goto yy57;
              } else {
                if (yych == 0xB0) goto yy57;
                if (yych <= 0xBE) goto yy84;
                goto yy57;
              }
yy166:
              yych = *++sp;
              if (yych <= 0x8B) {
                if (yych <= 0x7F) goto yy57;
                if (yych <= 0x8A) goto yy84;
                goto yy57;
              } else {
                if (yych <= 0x8C) goto yy84;
                if (yych <= 0x8F) goto yy57;
                if (yych <= 0xBF) goto yy84;
                goto yy57;
              }
yy167:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy168:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy169:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy170:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy171:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy172:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy173:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy174:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy175:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy176:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy177:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy178:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy179:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy180:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x8C) goto yy84;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0x99) goto yy84;
              goto yy57;
yy181:
              yych = *++sp;
              if (yych <= 0xB8) {
                if (yych <= 0xA4) goto yy57;
                if (yych <= 0xAA) goto yy84;
                goto yy57;
              } else {
                if (yych == 0xBD) goto yy57;
                if (yych <= 0xBF) goto yy84;
                goto yy57;
              }
yy182:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych == 0x9A) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy183:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xB3) goto yy84;
              goto yy57;
yy184:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy185:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy186:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy187:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x95) goto yy84;
              if (yych <= 0xAF) goto yy57;
              if (yych <= 0xBB) goto yy84;
              goto yy57;
yy188:
              yych = *++sp;
              if (yych <= '.') {
                if (yych <= 0x00) goto yy100;
                if (yych <= ',') goto yy105;
                if (yych <= '-') goto yy101;
                goto yy106;
              } else {
                if (yych <= 0xC2) {
                  if (yych <= 0xC1) goto yy105;
                  goto yy103;
                } else {
                  if (yych == 0xE2) goto yy104;
                  goto yy105;
                }
              }
yy189:
              yych = *++sp;
              if (yych <= 0xAF) goto yy57;
              if (yych <= 0xBE) goto yy84;
              goto yy57;
yy190:
              yych = *++sp;
              if (yych <= 0xA3) goto yy57;
              if (yych <= 0xA5) goto yy84;
              if (yych == 0xB0) goto yy84;
              goto yy57;
yy191:
              yych = *++sp;
              if (yych <= 0xB9) {
                if (yych <= 0xB1) goto yy57;
                if (yych <= 0xB3) goto yy124;
                goto yy57;
              } else {
                if (yych <= 0xBA) goto yy84;
                if (yych <= 0xBB) goto yy124;
                goto yy57;
              }
yy192:
              yych = *++sp;
              if (yych == 0xB1) goto yy124;
              goto yy57;
yy193:
              yych = *++sp;
              if (yych == 0xB0) goto yy84;
              goto yy57;
yy194:
              yych = *++sp;
              if (yych <= 0xB2) goto yy57;
              if (yych == 0xB9) goto yy124;
              if (yych <= 0xBA) goto yy84;
              goto yy57;
yy195:
              yych = *++sp;
              if (yych == 0xBF) goto yy84;
              goto yy57;
yy196:
              yych = *++sp;
              if (yych <= 0xB0) goto yy57;
              if (yych <= 0xB2) goto yy84;
              goto yy57;
yy197:
              yych = *++sp;
              if (yych == 0xB9) goto yy84;
              goto yy57;
yy198:
              yych = *++sp;
              if (yych == 0xB4) goto yy84;
              goto yy57;
yy199:
              yych = *++sp;
              if (yych == 0xBF) goto yy124;
              goto yy57;
yy200:
              yych = *++sp;
              if (yych == 0x8F) goto yy84;
              if (yych <= 0x99) goto yy57;
              if (yych <= 0x9B) goto yy84;
              goto yy57;
yy201:
              yych = *++sp;
              if (yych <= 0xB4) {
                if (yych <= 0x99) {
                  if (yych <= 0x80) goto yy57;
                  if (yych <= 0x97) goto yy84;
                  goto yy57;
                } else {
                  if (yych <= 0x9F) goto yy84;
                  if (yych <= 0xB3) goto yy57;
                  goto yy84;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych == 0xB6) goto yy84;
                  goto yy57;
                } else {
                  if (yych == 0xB9) goto yy57;
                  if (yych <= 0xBD) goto yy84;
                  goto yy57;
                }
              }
yy202:
              yych = *++sp;
              if (yych == 0x85) goto yy84;
              if (yych <= 0xBD) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy203:
              yych = *++sp;
              if (yych <= 0x86) {
                if (yych <= 0x7F) goto yy57;
                if (yych <= 0x85) goto yy84;
                goto yy57;
              } else {
                if (yych == 0x8D) goto yy57;
                if (yych <= 0x98) goto yy84;
                goto yy57;
              }
yy204:
              yych = *++sp;
              if (yych <= 0x89) goto yy57;
              if (yych <= 0x8F) goto yy84;
              goto yy57;
yy205:
              yych = *++sp;
              if (yych <= 0x9D) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy206:
              yych = *++sp;
              if (yych == 0xBB) goto yy84;
              goto yy57;
yy207:
              yych = *++sp;
              if (yych <= 0x9F) goto yy57;
              if (yych <= 0xA8) goto yy84;
              goto yy57;
yy208:
              yych = *++sp;
              if (yych <= 0x8F) goto yy57;
              if (yych <= 0x99) goto yy84;
              goto yy57;
yy209:
              yych = *++sp;
              if (yych == 0x80) goto yy84;
              goto yy57;
yy210:
              yych = *++sp;
              if (yych <= 0xAC) goto yy57;
              if (yych <= 0xAE) goto yy84;
              goto yy57;
yy211:
              yych = *++sp;
              if (yych <= 0x9A) goto yy57;
              if (yych <= 0x9C) goto yy84;
              goto yy57;
yy212:
              yych = *++sp;
              if (yych <= 0xAA) goto yy57;
              if (yych <= 0xAD) goto yy84;
              goto yy57;
yy213:
              yych = *++sp;
              if (yych <= 0xB4) goto yy57;
              if (yych <= 0xB6) goto yy84;
              goto yy57;
yy214:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych <= 0x93) goto yy57;
                if (yych <= 0x96) goto yy84;
                goto yy57;
              } else {
                if (yych <= 0x9A) goto yy84;
                if (yych <= 0x9B) goto yy124;
                goto yy57;
              }
yy215:
              yych = *++sp;
              if (yych <= 0x7F) goto yy57;
              if (yych <= 0x8A) goto yy84;
              goto yy57;
yy216:
              yych = *++sp;
              if (yych == 0x80) goto yy84;
              if (yych <= 0x83) goto yy57;
              if (yych <= 0x85) goto yy84;
              goto yy57;
yy217:
              yych = *++sp;
              if (yych <= 0x9D) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy218:
              yych = *++sp;
              if (yych <= 0x9D) goto yy57;
              if (yych <= 0x9F) goto yy84;
              goto yy57;
yy219:
              yych = *++sp;
              if (yych <= 0x9F) goto yy57;
              if (yych == 0xA7) goto yy57;
              if (yych <= 0xAD) goto yy84;
              goto yy57;
yy220:
              yych = *++sp;
              if (yych <= 0x99) goto yy57;
              if (yych <= 0xAA) goto yy84;
              if (yych <= 0xB3) goto yy57;
              if (yych <= 0xBC) goto yy84;
              goto yy57;
yy221:
              yych = *++sp;
              if (yych <= 0xBA) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy222:
              yych = *++sp;
              if (yych <= 0xBD) goto yy57;
              if (yych <= 0xBF) goto yy84;
              goto yy57;
yy223:
              yych = *++sp;
              if (yych == 0x93) goto yy84;
              goto yy57;
yy224:
              yych = *++sp;
              if (yych == 0xBD) goto yy84;
              if (yych == 0xBF) goto yy84;
              goto yy57;
yy225:
              yych = *++sp;
              if (yych <= 0x9C) {
                if (yych <= 0x81) {
                  if (yych <= 0x7F) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0x8C) goto yy57;
                  if (yych <= 0x8F) goto yy84;
                  goto yy57;
                }
              } else {
                if (yych <= 0xAF) {
                  if (yych <= 0x9F) goto yy84;
                  if (yych <= 0xAC) goto yy57;
                  goto yy84;
                } else {
                  if (yych <= 0xBC) goto yy57;
                  if (yych <= 0xBE) goto yy84;
                  goto yy57;
                }
              }
yy226:
              yych = *++sp;
              if (yych >= 0x01) goto yy57;
              ++sp;
              { annot3("NN","$(","$PARAGRAPH"); /*-- use double quotes and not [] in pattern for non-ascii symbols! --*/ }
yy229:
              ++sp;
              { annot3("NN","$(","$PERCENT"); }
yy231:
              ++sp;
              { annot1("$."); }
yy233:
              ++sp;
              { annot1("$,"); }
yy235:
              ++sp;
              yych = *sp;
              if (yych <= '.') {
                if (yych <= '!') {
                  if (yych <= 0x00) goto yy239;
                  if (yych <= ' ') goto yy56;
                  goto yy235;
                } else {
                  if (yych <= ',') goto yy56;
                  if (yych <= '-') goto yy50;
                  goto yy58;
                }
              } else {
                if (yych <= 0xC1) {
                  if (yych == '?') goto yy235;
                  goto yy56;
                } else {
                  if (yych <= 0xC2) goto yy52;
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy237:
              ++sp;
yy238:
              { annot1("$."); }
yy239:
              yych = *++sp;
              goto yy238;
yy240:
              ++sp;
              yych = *sp;
              if (yych <= '9') {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy247;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy240;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= ':') goto yy242;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy242:
              ++sp;
              yych = *sp;
              if (yych <= '9') {
                if (yych <= ',') {
                  if (yych <= 0x00) goto yy246;
                  goto yy56;
                } else {
                  if (yych <= '-') goto yy50;
                  if (yych <= '.') goto yy240;
                  goto yy56;
                }
              } else {
                if (yych <= 0xC2) {
                  if (yych <= ':') goto yy242;
                  if (yych <= 0xC1) goto yy56;
                  goto yy52;
                } else {
                  if (yych == 0xE2) goto yy54;
                  goto yy56;
                }
              }
yy244:
              ++sp;
yy245:
              { annot2("$.","$("); }
yy246:
              yych = *++sp;
              goto yy245;
yy247:
              yych = *++sp;
              goto yy245;
yy248:
              ++sp;
              { annot1("$."); }
            }

  }

#undef annot0
#undef annot1
#undef annot2
#undef annot3
#undef annot4

} // namespace moot
