/* Generated by re2c 0.13.5 on Tue Dec  3 18:06:09 2013 */
#include "wasteAnnotator.h"

namespace moot {

  void wasteAnnotator::annotate_token(mootToken& token)
  {
    const unsigned char *sp  = (const unsigned char*)token.tok_text.c_str();
    const unsigned char *m   = sp;

    

    //-- Auto-generated property rules go here
    

    //-- Manual definitions
    

    
            {
              unsigned char yych;
              unsigned int yyaccept = 0;

              yych = *sp;
              if (yych <= 0xCA) {
                if (yych <= '9') {
                  if (yych <= '\'') {
                    if (yych <= '#') {
                      if (yych <= ' ') goto yy38;
                      if (yych <= '!') goto yy4;
                      goto yy16;
                    } else {
                      if (yych <= '$') goto yy9;
                      if (yych <= '%') goto yy6;
                      if (yych <= '&') goto yy16;
                      goto yy17;
                    }
                  } else {
                    if (yych <= ',') {
                      if (yych <= '*') goto yy16;
                      if (yych <= '+') goto yy18;
                      goto yy5;
                    } else {
                      if (yych <= '-') goto yy19;
                      if (yych <= '.') goto yy2;
                      if (yych <= '/') goto yy16;
                      goto yy37;
                    }
                  }
                } else {
                  if (yych <= 'z') {
                    if (yych <= '@') {
                      if (yych == '?') goto yy4;
                      goto yy16;
                    } else {
                      if (yych <= 'Z') goto yy38;
                      if (yych <= '_') goto yy16;
                      if (yych <= '`') goto yy21;
                      goto yy38;
                    }
                  } else {
                    if (yych <= 0xA7) {
                      if (yych <= '~') goto yy16;
                      if (yych <= 0xA6) goto yy38;
                      goto yy7;
                    } else {
                      if (yych <= 0xC1) goto yy38;
                      if (yych <= 0xC2) goto yy8;
                      if (yych <= 0xC3) goto yy33;
                      goto yy38;
                    }
                  }
                }
              } else {
                if (yych <= 0xDA) {
                  if (yych <= 0xD2) {
                    if (yych <= 0xCD) {
                      if (yych <= 0xCB) goto yy32;
                      if (yych <= 0xCC) goto yy38;
                      goto yy24;
                    } else {
                      if (yych <= 0xCE) goto yy25;
                      if (yych <= 0xCF) goto yy34;
                      if (yych <= 0xD1) goto yy38;
                      goto yy35;
                    }
                  } else {
                    if (yych <= 0xD6) {
                      if (yych <= 0xD4) goto yy38;
                      if (yych <= 0xD5) goto yy26;
                      goto yy22;
                    } else {
                      if (yych <= 0xD7) goto yy27;
                      if (yych <= 0xD8) goto yy10;
                      if (yych <= 0xD9) goto yy28;
                      goto yy38;
                    }
                  }
                } else {
                  if (yych <= 0xE2) {
                    if (yych <= 0xDE) {
                      if (yych <= 0xDB) goto yy29;
                      if (yych <= 0xDC) goto yy30;
                      goto yy38;
                    } else {
                      if (yych <= 0xDF) goto yy31;
                      if (yych <= 0xE0) goto yy12;
                      if (yych <= 0xE1) goto yy11;
                      goto yy13;
                    }
                  } else {
                    if (yych <= 0xE9) {
                      if (yych <= 0xE3) goto yy23;
                      if (yych <= 0xE4) goto yy36;
                      goto yy38;
                    } else {
                      if (yych <= 0xEA) goto yy15;
                      if (yych == 0xEF) goto yy14;
                      goto yy38;
                    }
                  }
                }
              }
yy2:
              ++sp;
              if ((yych = *sp) <= 0x00) goto yy192;
yy3:
              { return; }
yy4:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '!') {
                if (yych <= 0x00) goto yy187;
                if (yych <= ' ') goto yy3;
                goto yy189;
              } else {
                if (yych == '?') goto yy189;
                goto yy3;
              }
yy5:
              yych = *++sp;
              if (yych <= 0x00) goto yy185;
              goto yy3;
yy6:
              yych = *++sp;
              if (yych <= 0x00) goto yy183;
              goto yy3;
yy7:
              yych = *++sp;
              if (yych <= 0x00) goto yy181;
              goto yy3;
yy8:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB1) {
                if (yych <= 0xA5) {
                  if (yych <= 0x00) goto yy181;
                  if (yych <= 0xA0) goto yy3;
                  if (yych <= 0xA1) goto yy48;
                  goto yy80;
                } else {
                  if (yych <= 0xAA) {
                    if (yych <= 0xA9) goto yy48;
                    goto yy3;
                  } else {
                    if (yych == 0xAD) goto yy3;
                    goto yy48;
                  }
                }
              } else {
                if (yych <= 0xB8) {
                  if (yych == 0xB4) goto yy48;
                  if (yych <= 0xB5) goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 0xBB) {
                    if (yych <= 0xBA) goto yy3;
                    goto yy48;
                  } else {
                    if (yych == 0xBF) goto yy48;
                    goto yy3;
                  }
                }
              }
yy9:
              yych = *++sp;
              if (yych <= 0x00) goto yy81;
              goto yy3;
yy10:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x8F) {
                if (yych <= 0x85) goto yy3;
                if (yych == 0x8B) goto yy80;
                goto yy48;
              } else {
                if (yych <= 0x9B) {
                  if (yych <= 0x9A) goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 0x9D) goto yy3;
                  if (yych <= 0x9F) goto yy48;
                  goto yy3;
                }
              }
yy11:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x81:  goto yy179;
              case 0x82:  goto yy164;
              case 0x83:  goto yy177;
              case 0x8D:  goto yy161;
              case 0x8E:  goto yy159;
              case 0x90:  goto yy180;
              case 0x99:  goto yy171;
              case 0x9A:  goto yy167;
              case 0x9B:  goto yy170;
              case 0x9C:  goto yy169;
              case 0x9F:  goto yy168;
              case 0xA0:  goto yy178;
              case 0xA5:  goto yy163;
              case 0xA7:  goto yy162;
              case 0xA8:  goto yy176;
              case 0xAA:  goto yy175;
              case 0xAD:  goto yy160;
              case 0xB0:  goto yy173;
              case 0xB1:  goto yy174;
              case 0xB3:  goto yy172;
              case 0xBE:  goto yy165;
              case 0xBF:  goto yy166;
              default:  goto yy3;
              }
yy12:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0xA0:  goto yy156;
              case 0xA5:  goto yy155;
              case 0xA7:  goto yy152;
              case 0xAB:  goto yy157;
              case 0xAD:  goto yy151;
              case 0xAF:  goto yy150;
              case 0xB1:  goto yy149;
              case 0xB3:  goto yy148;
              case 0xB5:  goto yy147;
              case 0xB7:  goto yy154;
              case 0xB8:  goto yy158;
              case 0xB9:  goto yy153;
              case 0xBC:  goto yy146;
              case 0xBE:  goto yy144;
              case 0xBF:  goto yy145;
              default:  goto yy3;
              }
yy13:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x80:  goto yy91;
              case 0x81:  goto yy142;
              case 0x82:  goto yy141;
              case 0x84:  goto yy126;
              case 0x85:  goto yy127;
              case 0x86:  goto yy124;
              case 0x87:  goto yy125;
              case 0x88:  goto yy139;
              case 0x89:  goto yy140;
              case 0x8A:  goto yy137;
              case 0x8B:  goto yy138;
              case 0x8C:  goto yy122;
              case 0x8D:  goto yy123;
              case 0x8E:  goto yy120;
              case 0x8F:  goto yy121;
              case 0x90:  goto yy118;
              case 0x91:  goto yy119;
              case 0x92:  goto yy116;
              case 0x93:  goto yy117;
              case 0x94:  goto yy114;
              case 0x95:  goto yy115;
              case 0x96:  goto yy112;
              case 0x97:  goto yy113;
              case 0x98:  goto yy110;
              case 0x99:  goto yy111;
              case 0x9A:  goto yy108;
              case 0x9B:  goto yy109;
              case 0x9C:  goto yy106;
              case 0x9D:  goto yy107;
              case 0x9E:  goto yy105;
              case 0x9F:  goto yy136;
              case 0xA0:  goto yy103;
              case 0xA1:  goto yy104;
              case 0xA2:  goto yy101;
              case 0xA3:  goto yy102;
              case 0xA4:  goto yy134;
              case 0xA5:  goto yy135;
              case 0xA6:  goto yy132;
              case 0xA7:  goto yy133;
              case 0xA8:  goto yy130;
              case 0xA9:  goto yy131;
              case 0xAA:  goto yy128;
              case 0xAB:  goto yy129;
              case 0xAC:  goto yy99;
              case 0xAD:  goto yy100;
              case 0xB3:  goto yy98;
              case 0xB8:  goto yy143;
              case 0xBA:  goto yy96;
              case 0xBB:  goto yy97;
              case 0xBC:  goto yy94;
              case 0xBD:  goto yy95;
              case 0xBE:  goto yy92;
              case 0xBF:  goto yy93;
              default:  goto yy3;
              }
yy14:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0xAC:  goto yy86;
              case 0xB4:  goto yy89;
              case 0xB7:  goto yy83;
              case 0xB8:  goto yy90;
              case 0xB9:  goto yy88;
              case 0xBC:  goto yy85;
              case 0xBD:  goto yy87;
              case 0xBF:  goto yy84;
              default:  goto yy3;
              }
yy15:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x92:  goto yy64;
              case 0x93:  goto yy65;
              case 0x98:  goto yy71;
              case 0x99:  goto yy72;
              case 0x9B:  goto yy70;
              case 0x9C:  goto yy69;
              case 0x9E:  goto yy68;
              case 0xA0:  goto yy66;
              case 0xA1:  goto yy79;
              case 0xA3:  goto yy78;
              case 0xA4:  goto yy76;
              case 0xA5:  goto yy77;
              case 0xA7:  goto yy75;
              case 0xA9:  goto yy67;
              case 0xAB:  goto yy74;
              case 0xAF:  goto yy73;
              default:  goto yy3;
              }
yy16:
              yych = *++sp;
              if (yych <= 0x00) goto yy49;
              goto yy3;
yy17:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy49;
              if (yych == '\'') goto yy48;
              goto yy3;
yy18:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy49;
              if (yych <= '/') goto yy3;
              if (yych <= '9') goto yy43;
              goto yy3;
yy19:
              yyaccept = 1;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy49;
              if (yych <= '/') goto yy20;
              if (yych <= '9') goto yy43;
yy20:
              { token.insert("TRUNC", ""); return; }
yy21:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy49;
              if (yych == '`') goto yy48;
              goto yy3;
yy22:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x88) goto yy3;
              if (yych <= 0x8A) goto yy48;
              if (yych == 0xBE) goto yy48;
              goto yy3;
yy23:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x80:  goto yy61;
              case 0x82:  goto yy62;
              case 0x83:  goto yy63;
              case 0x86:  goto yy59;
              case 0x87:  goto yy60;
              case 0x88:  goto yy57;
              case 0x89:  goto yy58;
              case 0x8A:  goto yy55;
              case 0x8B:  goto yy56;
              case 0x8C:  goto yy53;
              case 0x8D:  goto yy54;
              case 0x8E:  goto yy51;
              case 0x8F:  goto yy52;
              default:  goto yy3;
              }
yy24:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB5) goto yy48;
              if (yych == 0xBE) goto yy48;
              goto yy3;
yy25:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x83) goto yy3;
              if (yych == 0x86) goto yy3;
              if (yych <= 0x87) goto yy48;
              goto yy3;
yy26:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x99) goto yy3;
              if (yych <= 0x9F) goto yy48;
              goto yy3;
yy27:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x83) {
                if (yych == 0x80) goto yy48;
                if (yych <= 0x82) goto yy3;
                goto yy48;
              } else {
                if (yych <= 0x86) {
                  if (yych <= 0x85) goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 0xB2) goto yy3;
                  if (yych <= 0xB4) goto yy48;
                  goto yy3;
                }
              }
yy28:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA9) goto yy3;
              if (yych <= 0xAD) goto yy48;
              goto yy3;
yy29:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA8) {
                if (yych == 0x94) goto yy48;
                goto yy3;
              } else {
                if (yych <= 0xA9) goto yy48;
                if (yych <= 0xBC) goto yy3;
                if (yych <= 0xBE) goto yy48;
                goto yy3;
              }
yy30:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x7F) goto yy3;
              if (yych <= 0x8D) goto yy48;
              goto yy3;
yy31:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB5) goto yy3;
              if (yych <= 0xB9) goto yy48;
              goto yy3;
yy32:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA4) {
                if (yych <= 0x85) {
                  if (yych <= 0x81) goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 0x91) goto yy3;
                  if (yych <= 0x9F) goto yy48;
                  goto yy3;
                }
              } else {
                if (yych <= 0xAD) {
                  if (yych == 0xAC) goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 0xAE) goto yy3;
                  if (yych <= 0xBF) goto yy48;
                  goto yy3;
                }
              }
yy33:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0x97) goto yy48;
              if (yych == 0xB7) goto yy48;
              goto yy3;
yy34:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB6) goto yy48;
              goto yy3;
yy35:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0x82) goto yy48;
              goto yy3;
yy36:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB7) goto yy47;
              goto yy3;
yy37:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy44;
                  if (yych <= 0x1F) goto yy3;
                  goto yy44;
                } else {
                  if (yych == ',') goto yy44;
                  goto yy3;
                }
              } else {
                if (yych <= ':') {
                  if (yych == '/') goto yy3;
                  goto yy44;
                } else {
                  if (yych == '_') goto yy44;
                  goto yy3;
                }
              }
yy38:
              yych = *++sp;
              goto yy3;
yy39:
              ++sp;
              yych = *sp;
              if (yych <= '/') goto yy40;
              if (yych <= '9') goto yy45;
yy40:
              sp = m;
              if (yyaccept <= 0) {
                goto yy3;
              } else {
                goto yy20;
              }
yy41:
              ++sp;
              { token.insert("CARD",""); return; }
yy43:
              ++sp;
              yych = *sp;
yy44:
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy41;
                  if (yych <= 0x1F) goto yy40;
                  goto yy39;
                } else {
                  if (yych == ',') goto yy39;
                  goto yy40;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy39;
                  if (yych <= '/') goto yy40;
                  goto yy43;
                } else {
                  if (yych <= ':') goto yy39;
                  if (yych == '_') goto yy39;
                  goto yy40;
                }
              }
yy45:
              ++sp;
              yych = *sp;
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy41;
                  if (yych <= 0x1F) goto yy40;
                  goto yy39;
                } else {
                  if (yych == ',') goto yy39;
                  goto yy40;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy39;
                  if (yych <= '/') goto yy40;
                  goto yy45;
                } else {
                  if (yych <= ':') goto yy39;
                  if (yych == '_') goto yy39;
                  goto yy40;
                }
              }
yy47:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych >= 0xC0) goto yy40;
yy48:
              yych = *++sp;
              if (yych >= 0x01) goto yy40;
yy49:
              ++sp;
              { token.insert("$(",""); return; }
yy51:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy52:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy53:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy54:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy55:
              yych = *++sp;
              if (yych <= 0x89) goto yy40;
              if (yych <= 0xB0) goto yy48;
              goto yy40;
yy56:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBE) goto yy48;
              goto yy40;
yy57:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x9E) goto yy48;
              if (yych <= 0xA9) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy58:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x90) goto yy48;
              if (yych <= 0x9F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy59:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0x91) goto yy48;
              if (yych <= 0x95) goto yy40;
              if (yych <= 0x9F) goto yy48;
              goto yy40;
yy60:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xA3) goto yy48;
              goto yy40;
yy61:
              yych = *++sp;
              if (yych <= 0xAF) {
                if (yych <= 0x84) {
                  if (yych <= 0x80) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0x87) goto yy40;
                  if (yych <= 0xA0) goto yy48;
                  goto yy40;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych <= 0xB0) goto yy48;
                  if (yych <= 0xB5) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xBC) goto yy40;
                  if (yych <= 0xBF) goto yy48;
                  goto yy40;
                }
              }
yy62:
              yych = *++sp;
              if (yych <= 0x9A) goto yy40;
              if (yych <= 0x9C) goto yy48;
              if (yych == 0xA0) goto yy48;
              goto yy40;
yy63:
              yych = *++sp;
              if (yych == 0xBB) goto yy48;
              goto yy40;
yy64:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy65:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x86) goto yy48;
              if (yych <= 0xBD) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy66:
              yych = *++sp;
              if (yych <= 0xB5) {
                if (yych <= 0xA7) goto yy40;
                if (yych <= 0xAB) goto yy48;
                goto yy40;
              } else {
                if (yych == 0xB8) goto yy80;
                if (yych <= 0xB9) goto yy48;
                goto yy40;
              }
yy67:
              yych = *++sp;
              if (yych <= 0x9B) goto yy40;
              if (yych <= 0x9F) goto yy48;
              if (yych <= 0xB6) goto yy40;
              if (yych <= 0xB9) goto yy48;
              goto yy40;
yy68:
              yych = *++sp;
              if (yych <= 0x88) goto yy40;
              if (yych <= 0x8A) goto yy48;
              goto yy40;
yy69:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x96) goto yy48;
              if (yych <= 0x9F) goto yy40;
              if (yych <= 0xA1) goto yy48;
              goto yy40;
yy70:
              yych = *++sp;
              if (yych <= 0xB1) goto yy40;
              if (yych <= 0xB7) goto yy48;
              goto yy40;
yy71:
              yych = *++sp;
              if (yych <= 0x8C) goto yy40;
              if (yych <= 0x8F) goto yy48;
              goto yy40;
yy72:
              yych = *++sp;
              if (yych == 0xB3) goto yy48;
              if (yych == 0xBE) goto yy48;
              goto yy40;
yy73:
              yych = *++sp;
              if (yych == 0xAB) goto yy48;
              goto yy40;
yy74:
              yych = *++sp;
              if (yych <= 0x9D) goto yy40;
              if (yych <= 0x9F) goto yy48;
              goto yy40;
yy75:
              yych = *++sp;
              if (yych <= 0x80) goto yy40;
              if (yych <= 0x8D) goto yy48;
              if (yych <= 0x9D) goto yy40;
              if (yych <= 0x9F) goto yy48;
              goto yy40;
yy76:
              yych = *++sp;
              if (yych <= 0xAD) goto yy40;
              if (yych <= 0xAF) goto yy48;
              goto yy40;
yy77:
              yych = *++sp;
              if (yych == 0x9F) goto yy48;
              goto yy40;
yy78:
              yych = *++sp;
              if (yych <= 0x8D) goto yy40;
              if (yych <= 0x8F) goto yy48;
              if (yych <= 0xB7) goto yy40;
              if (yych <= 0xBA) goto yy48;
              goto yy40;
yy79:
              yych = *++sp;
              if (yych <= 0xB3) goto yy40;
              if (yych <= 0xB7) goto yy48;
              goto yy40;
yy80:
              yych = *++sp;
              if (yych >= 0x01) goto yy40;
yy81:
              ++sp;
              {
                                            token.insert("NN","");
                                            token.insert("$(","");
                                            token.insert("$CURRENCY","");
                                            return;
                                           }
yy83:
              yych = *++sp;
              if (yych <= 0xBB) goto yy40;
              if (yych <= 0xBC) goto yy80;
              if (yych <= 0xBD) goto yy48;
              goto yy40;
yy84:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x9F) goto yy40;
                if (yych <= 0xA1) goto yy80;
                if (yych <= 0xA4) goto yy48;
                goto yy80;
              } else {
                if (yych <= 0xAE) {
                  if (yych <= 0xA7) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xBB) goto yy40;
                  if (yych <= 0xBD) goto yy48;
                  goto yy40;
                }
              }
yy85:
              yych = *++sp;
              if (yych <= 0x8F) {
                if (yych <= 0x80) goto yy40;
                if (yych == 0x84) goto yy80;
                goto yy48;
              } else {
                if (yych <= 0xA0) {
                  if (yych <= 0x99) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xBA) goto yy40;
                  if (yych <= 0xBF) goto yy48;
                  goto yy40;
                }
              }
yy86:
              yych = *++sp;
              if (yych == 0xA9) goto yy48;
              goto yy40;
yy87:
              yych = *++sp;
              if (yych == 0x80) goto yy48;
              if (yych <= 0x9A) goto yy40;
              if (yych <= 0xA5) goto yy48;
              goto yy40;
yy88:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x7F) goto yy40;
                if (yych == 0x93) goto yy40;
                goto yy48;
              } else {
                if (yych <= 0xA8) {
                  if (yych <= 0xA7) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xA9) goto yy80;
                  if (yych <= 0xAB) goto yy48;
                  goto yy40;
                }
              }
yy89:
              yych = *++sp;
              if (yych <= 0xBD) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy90:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0x99) goto yy48;
              if (yych <= 0xAF) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy91:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0xA7) goto yy48;
              if (yych <= 0xAF) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy92:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy93:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x95) goto yy48;
              if (yych <= 0xAF) goto yy40;
              if (yych <= 0xBB) goto yy48;
              goto yy40;
yy94:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy95:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy96:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych == 0x9A) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy97:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xB3) goto yy48;
              goto yy40;
yy98:
              yych = *++sp;
              if (yych <= 0xB8) {
                if (yych <= 0xA4) goto yy40;
                if (yych <= 0xAA) goto yy48;
                goto yy40;
              } else {
                if (yych == 0xBD) goto yy40;
                if (yych <= 0xBF) goto yy48;
                goto yy40;
              }
yy99:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy100:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x8C) goto yy48;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0x99) goto yy48;
              goto yy40;
yy101:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy102:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy103:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy104:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy105:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych == 0x94) goto yy48;
                goto yy40;
              } else {
                if (yych == 0xB0) goto yy40;
                if (yych <= 0xBE) goto yy48;
                goto yy40;
              }
yy106:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x80) goto yy40;
                if (yych == 0x85) goto yy40;
                goto yy48;
              } else {
                if (yych <= 0xA7) {
                  if (yych <= 0x8B) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xA8) goto yy40;
                  if (yych <= 0xBF) goto yy48;
                  goto yy40;
                }
              }
yy107:
              yych = *++sp;
              if (yych <= 0x8E) {
                if (yych <= 0x8B) {
                  if (yych <= 0x7F) goto yy40;
                  goto yy48;
                } else {
                  if (yych == 0x8D) goto yy48;
                  goto yy40;
                }
              } else {
                if (yych <= 0x9E) {
                  if (yych <= 0x92) goto yy48;
                  if (yych <= 0x95) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xA0) goto yy40;
                  if (yych <= 0xB5) goto yy48;
                  goto yy40;
                }
              }
yy108:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy109:
              yych = *++sp;
              if (yych <= 0xA1) {
                if (yych <= 0x7F) goto yy40;
                if (yych == 0x8E) goto yy40;
                goto yy48;
              } else {
                if (yych <= 0xA3) {
                  if (yych <= 0xA2) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xA7) goto yy40;
                  if (yych <= 0xBF) goto yy48;
                  goto yy40;
                }
              }
yy110:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy111:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy112:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy113:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy114:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy115:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy116:
              yych = *++sp;
              if (yych <= 0x9B) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy117:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xA9) goto yy48;
              goto yy40;
yy118:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xA6) goto yy48;
              goto yy40;
yy119:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x8A) goto yy48;
              goto yy40;
yy120:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy121:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xA8) goto yy48;
              goto yy40;
yy122:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy123:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy124:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy125:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy126:
              yych = *++sp;
              switch (yych) {
              case 0x80:
              case 0x81:
              case 0x83:
              case 0x84:
              case 0x85:
              case 0x86:
              case 0x88:
              case 0x89:
              case 0x94:
              case 0x96:
              case 0x97:
              case 0x98:
              case 0x9E:
              case 0x9F:
              case 0xA0:
              case 0xA1:
              case 0xA2:
              case 0xA3:
              case 0xA5:
              case 0xA7:
              case 0xA9:
              case 0xAE:
              case 0xBA:
              case 0xBB:  goto yy48;
              default:  goto yy40;
              }
yy127:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x7F) goto yy40;
                if (yych <= 0x84) goto yy48;
                goto yy40;
              } else {
                if (yych == 0x8E) goto yy40;
                if (yych <= 0x8F) goto yy48;
                goto yy40;
              }
yy128:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy129:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy130:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy131:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy132:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy133:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy134:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy135:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy136:
              yych = *++sp;
              if (yych <= 0x8B) {
                if (yych <= 0x7F) goto yy40;
                if (yych <= 0x8A) goto yy48;
                goto yy40;
              } else {
                if (yych <= 0x8C) goto yy48;
                if (yych <= 0x8F) goto yy40;
                if (yych <= 0xBF) goto yy48;
                goto yy40;
              }
yy137:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy138:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy139:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy140:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy141:
              yych = *++sp;
              if (yych <= 0x89) goto yy40;
              if (yych <= 0x8E) goto yy48;
              if (yych <= 0x9F) goto yy40;
              if (yych <= 0xB8) goto yy80;
              goto yy40;
yy142:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x9E) goto yy48;
              if (yych <= 0xB9) goto yy40;
              if (yych <= 0xBE) goto yy48;
              goto yy40;
yy143:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych == 0xAF) goto yy40;
              if (yych <= 0xB1) goto yy48;
              goto yy40;
yy144:
              yych = *++sp;
              if (yych == 0x85) goto yy48;
              if (yych <= 0xBD) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy145:
              yych = *++sp;
              if (yych <= 0x86) {
                if (yych <= 0x7F) goto yy40;
                if (yych <= 0x85) goto yy48;
                goto yy40;
              } else {
                if (yych == 0x8D) goto yy40;
                if (yych <= 0x98) goto yy48;
                goto yy40;
              }
yy146:
              yych = *++sp;
              if (yych <= 0xB4) {
                if (yych <= 0x99) {
                  if (yych <= 0x80) goto yy40;
                  if (yych <= 0x97) goto yy48;
                  goto yy40;
                } else {
                  if (yych <= 0x9F) goto yy48;
                  if (yych <= 0xB3) goto yy40;
                  goto yy48;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych == 0xB6) goto yy48;
                  goto yy40;
                } else {
                  if (yych == 0xB9) goto yy40;
                  if (yych <= 0xBD) goto yy48;
                  goto yy40;
                }
              }
yy147:
              yych = *++sp;
              if (yych == 0xB9) goto yy48;
              goto yy40;
yy148:
              yych = *++sp;
              if (yych <= 0xB0) goto yy40;
              if (yych <= 0xB2) goto yy48;
              goto yy40;
yy149:
              yych = *++sp;
              if (yych == 0xBF) goto yy48;
              goto yy40;
yy150:
              yych = *++sp;
              if (yych <= 0xB2) goto yy40;
              if (yych == 0xB9) goto yy80;
              if (yych <= 0xBA) goto yy48;
              goto yy40;
yy151:
              yych = *++sp;
              if (yych == 0xB0) goto yy48;
              goto yy40;
yy152:
              yych = *++sp;
              if (yych <= 0xB9) {
                if (yych <= 0xB1) goto yy40;
                if (yych <= 0xB3) goto yy80;
                goto yy40;
              } else {
                if (yych <= 0xBA) goto yy48;
                if (yych <= 0xBB) goto yy80;
                goto yy40;
              }
yy153:
              yych = *++sp;
              if (yych == 0x8F) goto yy48;
              if (yych <= 0x99) goto yy40;
              if (yych <= 0x9B) goto yy48;
              goto yy40;
yy154:
              yych = *++sp;
              if (yych == 0xB4) goto yy48;
              goto yy40;
yy155:
              yych = *++sp;
              if (yych <= 0xA3) goto yy40;
              if (yych <= 0xA5) goto yy48;
              if (yych == 0xB0) goto yy48;
              goto yy40;
yy156:
              yych = *++sp;
              if (yych <= 0xAF) goto yy40;
              if (yych <= 0xBE) goto yy48;
              goto yy40;
yy157:
              yych = *++sp;
              if (yych == 0xB1) goto yy80;
              goto yy40;
yy158:
              yych = *++sp;
              if (yych == 0xBF) goto yy80;
              goto yy40;
yy159:
              yych = *++sp;
              if (yych <= 0x8F) goto yy40;
              if (yych <= 0x99) goto yy48;
              goto yy40;
yy160:
              yych = *++sp;
              if (yych <= 0x99) goto yy40;
              if (yych <= 0xAA) goto yy48;
              if (yych <= 0xB3) goto yy40;
              if (yych <= 0xBC) goto yy48;
              goto yy40;
yy161:
              yych = *++sp;
              if (yych <= 0x9F) goto yy40;
              if (yych <= 0xA8) goto yy48;
              goto yy40;
yy162:
              yych = *++sp;
              if (yych <= 0x9D) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy163:
              yych = *++sp;
              if (yych == 0x80) goto yy48;
              if (yych <= 0x83) goto yy40;
              if (yych <= 0x85) goto yy48;
              goto yy40;
yy164:
              yych = *++sp;
              if (yych <= 0x9D) goto yy40;
              if (yych <= 0x9F) goto yy48;
              goto yy40;
yy165:
              yych = *++sp;
              if (yych == 0xBD) goto yy48;
              if (yych == 0xBF) goto yy48;
              goto yy40;
yy166:
              yych = *++sp;
              if (yych <= 0x9C) {
                if (yych <= 0x81) {
                  if (yych <= 0x7F) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0x8C) goto yy40;
                  if (yych <= 0x8F) goto yy48;
                  goto yy40;
                }
              } else {
                if (yych <= 0xAF) {
                  if (yych <= 0x9F) goto yy48;
                  if (yych <= 0xAC) goto yy40;
                  goto yy48;
                } else {
                  if (yych <= 0xBC) goto yy40;
                  if (yych <= 0xBE) goto yy48;
                  goto yy40;
                }
              }
yy167:
              yych = *++sp;
              if (yych <= 0x9A) goto yy40;
              if (yych <= 0x9C) goto yy48;
              goto yy40;
yy168:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych <= 0x93) goto yy40;
                if (yych <= 0x96) goto yy48;
                goto yy40;
              } else {
                if (yych <= 0x9A) goto yy48;
                if (yych <= 0x9B) goto yy80;
                goto yy40;
              }
yy169:
              yych = *++sp;
              if (yych <= 0xB4) goto yy40;
              if (yych <= 0xB6) goto yy48;
              goto yy40;
yy170:
              yych = *++sp;
              if (yych <= 0xAA) goto yy40;
              if (yych <= 0xAD) goto yy48;
              goto yy40;
yy171:
              yych = *++sp;
              if (yych <= 0xAC) goto yy40;
              if (yych <= 0xAE) goto yy48;
              goto yy40;
yy172:
              yych = *++sp;
              if (yych == 0x93) goto yy48;
              goto yy40;
yy173:
              yych = *++sp;
              if (yych <= 0xBA) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy174:
              yych = *++sp;
              if (yych <= 0xBD) goto yy40;
              if (yych <= 0xBF) goto yy48;
              goto yy40;
yy175:
              yych = *++sp;
              if (yych <= 0x9F) goto yy40;
              if (yych == 0xA7) goto yy40;
              if (yych <= 0xAD) goto yy48;
              goto yy40;
yy176:
              yych = *++sp;
              if (yych <= 0x9D) goto yy40;
              if (yych <= 0x9F) goto yy48;
              goto yy40;
yy177:
              yych = *++sp;
              if (yych == 0xBB) goto yy48;
              goto yy40;
yy178:
              yych = *++sp;
              if (yych <= 0x7F) goto yy40;
              if (yych <= 0x8A) goto yy48;
              goto yy40;
yy179:
              yych = *++sp;
              if (yych <= 0x89) goto yy40;
              if (yych <= 0x8F) goto yy48;
              goto yy40;
yy180:
              yych = *++sp;
              if (yych == 0x80) goto yy48;
              goto yy40;
yy181:
              ++sp;
              {
                                            token.insert("NN","");
                                            token.insert("$(","");
                                            token.insert("$PARAGRAPH","");
                                            return;
                                           }
yy183:
              ++sp;
              {
                                             token.insert("NN","");
                                             token.insert("$(","");
                                             token.insert("$PERCENT","");
                                             return;
                                           }
yy185:
              ++sp;
              { token.insert("$,",""); return; }
yy187:
              ++sp;
yy188:
              { token.insert("$.",""); return; }
yy189:
              ++sp;
              yych = *sp;
              if (yych <= '!') {
                if (yych <= 0x00) goto yy191;
                if (yych <= ' ') goto yy40;
                goto yy189;
              } else {
                if (yych == '?') goto yy189;
                goto yy40;
              }
yy191:
              yych = *++sp;
              goto yy188;
yy192:
              ++sp;
              { token.insert("$.",""); return; }
            }

  }

} // namespace moot
