/* Generated by re2c 0.13.5 on Wed Dec  4 10:17:23 2013 */
#include "wasteAnnotator.h"

namespace moot {

  void wasteAnnotator::annotate_token(mootToken& token)
  {
    const unsigned char *sp  = (const unsigned char*)token.tok_text.c_str();
    const unsigned char *m   = sp;

    

    //-- Auto-generated property rules go here
    

    //-- Manual definitions
    

    
            {
              unsigned char yych;
              unsigned int yyaccept = 0;

              yych = *sp;
              if (yych <= 0xC2) {
                if (yych <= ':') {
                  if (yych <= '\'') {
                    if (yych <= '#') {
                      if (yych <= ' ') goto yy42;
                      if (yych <= '!') goto yy5;
                      goto yy18;
                    } else {
                      if (yych <= '$') goto yy11;
                      if (yych <= '%') goto yy8;
                      if (yych <= '&') goto yy18;
                      goto yy19;
                    }
                  } else {
                    if (yych <= '-') {
                      if (yych <= '*') goto yy18;
                      if (yych <= '+') goto yy20;
                      if (yych <= ',') goto yy6;
                      goto yy21;
                    } else {
                      if (yych <= '.') goto yy2;
                      if (yych <= '/') goto yy18;
                      if (yych <= '9') goto yy39;
                      goto yy4;
                    }
                  }
                } else {
                  if (yych <= '`') {
                    if (yych <= '?') {
                      if (yych <= ';') goto yy7;
                      if (yych <= '>') goto yy18;
                      goto yy5;
                    } else {
                      if (yych <= '@') goto yy18;
                      if (yych <= 'Z') goto yy41;
                      if (yych <= '_') goto yy18;
                      goto yy23;
                    }
                  } else {
                    if (yych <= '~') {
                      if (yych == 'w') goto yy40;
                      if (yych <= 'z') goto yy41;
                      goto yy18;
                    } else {
                      if (yych == 0xA7) goto yy9;
                      if (yych <= 0xC1) goto yy42;
                      goto yy10;
                    }
                  }
                }
              } else {
                if (yych <= 0xD9) {
                  if (yych <= 0xCF) {
                    if (yych <= 0xCB) {
                      if (yych <= 0xC3) goto yy35;
                      if (yych <= 0xCA) goto yy42;
                      goto yy34;
                    } else {
                      if (yych <= 0xCC) goto yy42;
                      if (yych <= 0xCD) goto yy26;
                      if (yych <= 0xCE) goto yy27;
                      goto yy36;
                    }
                  } else {
                    if (yych <= 0xD5) {
                      if (yych == 0xD2) goto yy37;
                      if (yych <= 0xD4) goto yy42;
                      goto yy28;
                    } else {
                      if (yych <= 0xD6) goto yy24;
                      if (yych <= 0xD7) goto yy29;
                      if (yych <= 0xD8) goto yy12;
                      goto yy30;
                    }
                  }
                } else {
                  if (yych <= 0xE1) {
                    if (yych <= 0xDC) {
                      if (yych <= 0xDA) goto yy42;
                      if (yych <= 0xDB) goto yy31;
                      goto yy32;
                    } else {
                      if (yych <= 0xDE) goto yy42;
                      if (yych <= 0xDF) goto yy33;
                      if (yych <= 0xE0) goto yy14;
                      goto yy13;
                    }
                  } else {
                    if (yych <= 0xE9) {
                      if (yych <= 0xE2) goto yy15;
                      if (yych <= 0xE3) goto yy25;
                      if (yych <= 0xE4) goto yy38;
                      goto yy42;
                    } else {
                      if (yych <= 0xEA) goto yy17;
                      if (yych == 0xEF) goto yy16;
                      goto yy42;
                    }
                  }
                }
              }
yy2:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '.') {
                if (yych <= 0x00) goto yy213;
                if (yych >= '.') goto yy215;
              } else {
                if (yych == ':') goto yy210;
              }
yy3:
              { return; }
yy4:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '.') {
                if (yych <= 0x00) goto yy208;
                if (yych <= '-') goto yy3;
                goto yy210;
              } else {
                if (yych == ':') goto yy210;
                goto yy3;
              }
yy5:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '!') {
                if (yych <= 0x00) goto yy203;
                if (yych <= ' ') goto yy3;
                goto yy205;
              } else {
                if (yych == '?') goto yy205;
                goto yy3;
              }
yy6:
              yych = *++sp;
              if (yych <= 0x00) goto yy201;
              goto yy3;
yy7:
              yych = *++sp;
              if (yych <= 0x00) goto yy199;
              goto yy3;
yy8:
              yych = *++sp;
              if (yych <= 0x00) goto yy197;
              goto yy3;
yy9:
              yych = *++sp;
              if (yych <= 0x00) goto yy195;
              goto yy3;
yy10:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB1) {
                if (yych <= 0xA5) {
                  if (yych <= 0x00) goto yy195;
                  if (yych <= 0xA0) goto yy3;
                  if (yych <= 0xA1) goto yy62;
                  goto yy94;
                } else {
                  if (yych <= 0xAA) {
                    if (yych <= 0xA9) goto yy62;
                    goto yy3;
                  } else {
                    if (yych == 0xAD) goto yy3;
                    goto yy62;
                  }
                }
              } else {
                if (yych <= 0xB8) {
                  if (yych == 0xB4) goto yy62;
                  if (yych <= 0xB5) goto yy3;
                  goto yy62;
                } else {
                  if (yych <= 0xBB) {
                    if (yych <= 0xBA) goto yy3;
                    goto yy62;
                  } else {
                    if (yych == 0xBF) goto yy62;
                    goto yy3;
                  }
                }
              }
yy11:
              yych = *++sp;
              if (yych <= 0x00) goto yy95;
              goto yy3;
yy12:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x8F) {
                if (yych <= 0x85) goto yy3;
                if (yych == 0x8B) goto yy94;
                goto yy62;
              } else {
                if (yych <= 0x9B) {
                  if (yych <= 0x9A) goto yy3;
                  goto yy62;
                } else {
                  if (yych <= 0x9D) goto yy3;
                  if (yych <= 0x9F) goto yy62;
                  goto yy3;
                }
              }
yy13:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x81:  goto yy193;
              case 0x82:  goto yy178;
              case 0x83:  goto yy191;
              case 0x8D:  goto yy175;
              case 0x8E:  goto yy173;
              case 0x90:  goto yy194;
              case 0x99:  goto yy185;
              case 0x9A:  goto yy181;
              case 0x9B:  goto yy184;
              case 0x9C:  goto yy183;
              case 0x9F:  goto yy182;
              case 0xA0:  goto yy192;
              case 0xA5:  goto yy177;
              case 0xA7:  goto yy176;
              case 0xA8:  goto yy190;
              case 0xAA:  goto yy189;
              case 0xAD:  goto yy174;
              case 0xB0:  goto yy187;
              case 0xB1:  goto yy188;
              case 0xB3:  goto yy186;
              case 0xBE:  goto yy179;
              case 0xBF:  goto yy180;
              default:  goto yy3;
              }
yy14:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0xA0:  goto yy170;
              case 0xA5:  goto yy169;
              case 0xA7:  goto yy166;
              case 0xAB:  goto yy171;
              case 0xAD:  goto yy165;
              case 0xAF:  goto yy164;
              case 0xB1:  goto yy163;
              case 0xB3:  goto yy162;
              case 0xB5:  goto yy161;
              case 0xB7:  goto yy168;
              case 0xB8:  goto yy172;
              case 0xB9:  goto yy167;
              case 0xBC:  goto yy160;
              case 0xBE:  goto yy158;
              case 0xBF:  goto yy159;
              default:  goto yy3;
              }
yy15:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x80:  goto yy105;
              case 0x81:  goto yy156;
              case 0x82:  goto yy155;
              case 0x84:  goto yy140;
              case 0x85:  goto yy141;
              case 0x86:  goto yy138;
              case 0x87:  goto yy139;
              case 0x88:  goto yy153;
              case 0x89:  goto yy154;
              case 0x8A:  goto yy151;
              case 0x8B:  goto yy152;
              case 0x8C:  goto yy136;
              case 0x8D:  goto yy137;
              case 0x8E:  goto yy134;
              case 0x8F:  goto yy135;
              case 0x90:  goto yy132;
              case 0x91:  goto yy133;
              case 0x92:  goto yy130;
              case 0x93:  goto yy131;
              case 0x94:  goto yy128;
              case 0x95:  goto yy129;
              case 0x96:  goto yy126;
              case 0x97:  goto yy127;
              case 0x98:  goto yy124;
              case 0x99:  goto yy125;
              case 0x9A:  goto yy122;
              case 0x9B:  goto yy123;
              case 0x9C:  goto yy120;
              case 0x9D:  goto yy121;
              case 0x9E:  goto yy119;
              case 0x9F:  goto yy150;
              case 0xA0:  goto yy117;
              case 0xA1:  goto yy118;
              case 0xA2:  goto yy115;
              case 0xA3:  goto yy116;
              case 0xA4:  goto yy148;
              case 0xA5:  goto yy149;
              case 0xA6:  goto yy146;
              case 0xA7:  goto yy147;
              case 0xA8:  goto yy144;
              case 0xA9:  goto yy145;
              case 0xAA:  goto yy142;
              case 0xAB:  goto yy143;
              case 0xAC:  goto yy113;
              case 0xAD:  goto yy114;
              case 0xB3:  goto yy112;
              case 0xB8:  goto yy157;
              case 0xBA:  goto yy110;
              case 0xBB:  goto yy111;
              case 0xBC:  goto yy108;
              case 0xBD:  goto yy109;
              case 0xBE:  goto yy106;
              case 0xBF:  goto yy107;
              default:  goto yy3;
              }
yy16:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0xAC:  goto yy100;
              case 0xB4:  goto yy103;
              case 0xB7:  goto yy97;
              case 0xB8:  goto yy104;
              case 0xB9:  goto yy102;
              case 0xBC:  goto yy99;
              case 0xBD:  goto yy101;
              case 0xBF:  goto yy98;
              default:  goto yy3;
              }
yy17:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x92:  goto yy78;
              case 0x93:  goto yy79;
              case 0x98:  goto yy85;
              case 0x99:  goto yy86;
              case 0x9B:  goto yy84;
              case 0x9C:  goto yy83;
              case 0x9E:  goto yy82;
              case 0xA0:  goto yy80;
              case 0xA1:  goto yy93;
              case 0xA3:  goto yy92;
              case 0xA4:  goto yy90;
              case 0xA5:  goto yy91;
              case 0xA7:  goto yy89;
              case 0xA9:  goto yy81;
              case 0xAB:  goto yy88;
              case 0xAF:  goto yy87;
              default:  goto yy3;
              }
yy18:
              yych = *++sp;
              if (yych <= 0x00) goto yy63;
              goto yy3;
yy19:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy63;
              if (yych == '\'') goto yy62;
              goto yy3;
yy20:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy63;
              if (yych <= '/') goto yy3;
              if (yych <= '9') goto yy53;
              goto yy3;
yy21:
              yyaccept = 1;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy63;
              if (yych <= '/') goto yy22;
              if (yych <= '9') goto yy53;
yy22:
              { token.insert("TRUNC", ""); return; }
yy23:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x00) goto yy63;
              if (yych == '`') goto yy62;
              goto yy3;
yy24:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x88) goto yy3;
              if (yych <= 0x8A) goto yy62;
              if (yych == 0xBE) goto yy62;
              goto yy3;
yy25:
              yyaccept = 0;
              yych = *(m = ++sp);
              switch (yych) {
              case 0x80:  goto yy75;
              case 0x82:  goto yy76;
              case 0x83:  goto yy77;
              case 0x86:  goto yy73;
              case 0x87:  goto yy74;
              case 0x88:  goto yy71;
              case 0x89:  goto yy72;
              case 0x8A:  goto yy69;
              case 0x8B:  goto yy70;
              case 0x8C:  goto yy67;
              case 0x8D:  goto yy68;
              case 0x8E:  goto yy65;
              case 0x8F:  goto yy66;
              default:  goto yy3;
              }
yy26:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB5) goto yy62;
              if (yych == 0xBE) goto yy62;
              goto yy3;
yy27:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x83) goto yy3;
              if (yych == 0x86) goto yy3;
              if (yych <= 0x87) goto yy62;
              goto yy3;
yy28:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x99) goto yy3;
              if (yych <= 0x9F) goto yy62;
              goto yy3;
yy29:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x83) {
                if (yych == 0x80) goto yy62;
                if (yych <= 0x82) goto yy3;
                goto yy62;
              } else {
                if (yych <= 0x86) {
                  if (yych <= 0x85) goto yy3;
                  goto yy62;
                } else {
                  if (yych <= 0xB2) goto yy3;
                  if (yych <= 0xB4) goto yy62;
                  goto yy3;
                }
              }
yy30:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA9) goto yy3;
              if (yych <= 0xAD) goto yy62;
              goto yy3;
yy31:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA8) {
                if (yych == 0x94) goto yy62;
                goto yy3;
              } else {
                if (yych <= 0xA9) goto yy62;
                if (yych <= 0xBC) goto yy3;
                if (yych <= 0xBE) goto yy62;
                goto yy3;
              }
yy32:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0x7F) goto yy3;
              if (yych <= 0x8D) goto yy62;
              goto yy3;
yy33:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xB5) goto yy3;
              if (yych <= 0xB9) goto yy62;
              goto yy3;
yy34:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 0xA4) {
                if (yych <= 0x85) {
                  if (yych <= 0x81) goto yy3;
                  goto yy62;
                } else {
                  if (yych <= 0x91) goto yy3;
                  if (yych <= 0x9F) goto yy62;
                  goto yy3;
                }
              } else {
                if (yych <= 0xAD) {
                  if (yych == 0xAC) goto yy3;
                  goto yy62;
                } else {
                  if (yych <= 0xAE) goto yy3;
                  if (yych <= 0xBF) goto yy62;
                  goto yy3;
                }
              }
yy35:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0x97) goto yy62;
              if (yych == 0xB7) goto yy62;
              goto yy3;
yy36:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB6) goto yy62;
              goto yy3;
yy37:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0x82) goto yy62;
              goto yy3;
yy38:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych == 0xB7) goto yy61;
              goto yy3;
yy39:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy54;
                  if (yych <= 0x1F) goto yy3;
                  goto yy54;
                } else {
                  if (yych == ',') goto yy54;
                  goto yy3;
                }
              } else {
                if (yych <= ':') {
                  if (yych == '/') goto yy3;
                  goto yy54;
                } else {
                  if (yych == '_') goto yy54;
                  goto yy3;
                }
              }
yy40:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= 'Z') {
                if (yych == ':') goto yy48;
                if (yych <= '?') goto yy3;
                goto yy48;
              } else {
                if (yych <= 'v') {
                  if (yych <= '`') goto yy3;
                  goto yy48;
                } else {
                  if (yych <= 'w') goto yy49;
                  if (yych <= 'z') goto yy48;
                  goto yy3;
                }
              }
yy41:
              yyaccept = 0;
              yych = *(m = ++sp);
              if (yych <= '?') {
                if (yych == ':') goto yy48;
                goto yy3;
              } else {
                if (yych <= 'Z') goto yy48;
                if (yych <= '`') goto yy3;
                if (yych <= 'z') goto yy48;
                goto yy3;
              }
yy42:
              yych = *++sp;
              goto yy3;
yy43:
              ++sp;
              {
                                                   token.insert("NN","");
                                                   token.insert("NE","");
                                                   token.insert("XY","");
                                                   token.insert("$LINK","");
                                                   return;
                                                 }
yy45:
              yych = *++sp;
              if (yych == '/') goto yy43;
yy46:
              sp = m;
              if (yyaccept <= 0) {
                goto yy3;
              } else {
                goto yy22;
              }
yy47:
              ++sp;
              yych = *sp;
yy48:
              if (yych <= '@') {
                if (yych == ':') goto yy45;
                if (yych <= '?') goto yy46;
                goto yy43;
              } else {
                if (yych <= 'Z') goto yy47;
                if (yych <= '`') goto yy46;
                if (yych <= 'z') goto yy47;
                goto yy46;
              }
yy49:
              yych = *++sp;
              if (yych != 'w') goto yy48;
              yych = *++sp;
              if (yych == '.') goto yy43;
              goto yy48;
yy51:
              ++sp;
              yych = *sp;
              if (yych <= '/') goto yy46;
              if (yych <= '9') goto yy57;
              goto yy46;
yy52:
              ++sp;
              yych = *sp;
              if (yych <= 0x00) goto yy59;
              if (yych <= '/') goto yy46;
              if (yych <= '9') goto yy57;
              goto yy46;
yy53:
              ++sp;
              yych = *sp;
yy54:
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy55;
                  if (yych <= 0x1F) goto yy46;
                  goto yy51;
                } else {
                  if (yych == ',') goto yy51;
                  goto yy46;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy52;
                  if (yych <= '/') goto yy46;
                  goto yy53;
                } else {
                  if (yych <= ':') goto yy51;
                  if (yych == '_') goto yy51;
                  goto yy46;
                }
              }
yy55:
              ++sp;
              { token.insert("CARD",""); return; }
yy57:
              ++sp;
              yych = *sp;
              if (yych <= '-') {
                if (yych <= ' ') {
                  if (yych <= 0x00) goto yy55;
                  if (yych <= 0x1F) goto yy46;
                  goto yy51;
                } else {
                  if (yych == ',') goto yy51;
                  goto yy46;
                }
              } else {
                if (yych <= '9') {
                  if (yych <= '.') goto yy52;
                  if (yych <= '/') goto yy46;
                  goto yy57;
                } else {
                  if (yych <= ':') goto yy51;
                  if (yych == '_') goto yy51;
                  goto yy46;
                }
              }
yy59:
              ++sp;
              { token.insert("ORD",""); return; }
yy61:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych >= 0xC0) goto yy46;
yy62:
              yych = *++sp;
              if (yych >= 0x01) goto yy46;
yy63:
              ++sp;
              { token.insert("$(",""); return; }
yy65:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy66:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy67:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy68:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy69:
              yych = *++sp;
              if (yych <= 0x89) goto yy46;
              if (yych <= 0xB0) goto yy62;
              goto yy46;
yy70:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBE) goto yy62;
              goto yy46;
yy71:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x9E) goto yy62;
              if (yych <= 0xA9) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy72:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x90) goto yy62;
              if (yych <= 0x9F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy73:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0x91) goto yy62;
              if (yych <= 0x95) goto yy46;
              if (yych <= 0x9F) goto yy62;
              goto yy46;
yy74:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xA3) goto yy62;
              goto yy46;
yy75:
              yych = *++sp;
              if (yych <= 0xAF) {
                if (yych <= 0x84) {
                  if (yych <= 0x80) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0x87) goto yy46;
                  if (yych <= 0xA0) goto yy62;
                  goto yy46;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych <= 0xB0) goto yy62;
                  if (yych <= 0xB5) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xBC) goto yy46;
                  if (yych <= 0xBF) goto yy62;
                  goto yy46;
                }
              }
yy76:
              yych = *++sp;
              if (yych <= 0x9A) goto yy46;
              if (yych <= 0x9C) goto yy62;
              if (yych == 0xA0) goto yy62;
              goto yy46;
yy77:
              yych = *++sp;
              if (yych == 0xBB) goto yy62;
              goto yy46;
yy78:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy79:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x86) goto yy62;
              if (yych <= 0xBD) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy80:
              yych = *++sp;
              if (yych <= 0xB5) {
                if (yych <= 0xA7) goto yy46;
                if (yych <= 0xAB) goto yy62;
                goto yy46;
              } else {
                if (yych == 0xB8) goto yy94;
                if (yych <= 0xB9) goto yy62;
                goto yy46;
              }
yy81:
              yych = *++sp;
              if (yych <= 0x9B) goto yy46;
              if (yych <= 0x9F) goto yy62;
              if (yych <= 0xB6) goto yy46;
              if (yych <= 0xB9) goto yy62;
              goto yy46;
yy82:
              yych = *++sp;
              if (yych <= 0x88) goto yy46;
              if (yych <= 0x8A) goto yy62;
              goto yy46;
yy83:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x96) goto yy62;
              if (yych <= 0x9F) goto yy46;
              if (yych <= 0xA1) goto yy62;
              goto yy46;
yy84:
              yych = *++sp;
              if (yych <= 0xB1) goto yy46;
              if (yych <= 0xB7) goto yy62;
              goto yy46;
yy85:
              yych = *++sp;
              if (yych <= 0x8C) goto yy46;
              if (yych <= 0x8F) goto yy62;
              goto yy46;
yy86:
              yych = *++sp;
              if (yych == 0xB3) goto yy62;
              if (yych == 0xBE) goto yy62;
              goto yy46;
yy87:
              yych = *++sp;
              if (yych == 0xAB) goto yy62;
              goto yy46;
yy88:
              yych = *++sp;
              if (yych <= 0x9D) goto yy46;
              if (yych <= 0x9F) goto yy62;
              goto yy46;
yy89:
              yych = *++sp;
              if (yych <= 0x80) goto yy46;
              if (yych <= 0x8D) goto yy62;
              if (yych <= 0x9D) goto yy46;
              if (yych <= 0x9F) goto yy62;
              goto yy46;
yy90:
              yych = *++sp;
              if (yych <= 0xAD) goto yy46;
              if (yych <= 0xAF) goto yy62;
              goto yy46;
yy91:
              yych = *++sp;
              if (yych == 0x9F) goto yy62;
              goto yy46;
yy92:
              yych = *++sp;
              if (yych <= 0x8D) goto yy46;
              if (yych <= 0x8F) goto yy62;
              if (yych <= 0xB7) goto yy46;
              if (yych <= 0xBA) goto yy62;
              goto yy46;
yy93:
              yych = *++sp;
              if (yych <= 0xB3) goto yy46;
              if (yych <= 0xB7) goto yy62;
              goto yy46;
yy94:
              yych = *++sp;
              if (yych >= 0x01) goto yy46;
yy95:
              ++sp;
              {
                                                   token.insert("NN","");
                                                   token.insert("$(","");
                                                   token.insert("$CURRENCY","");
                                                   return;
                                                 }
yy97:
              yych = *++sp;
              if (yych <= 0xBB) goto yy46;
              if (yych <= 0xBC) goto yy94;
              if (yych <= 0xBD) goto yy62;
              goto yy46;
yy98:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x9F) goto yy46;
                if (yych <= 0xA1) goto yy94;
                if (yych <= 0xA4) goto yy62;
                goto yy94;
              } else {
                if (yych <= 0xAE) {
                  if (yych <= 0xA7) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xBB) goto yy46;
                  if (yych <= 0xBD) goto yy62;
                  goto yy46;
                }
              }
yy99:
              yych = *++sp;
              if (yych <= 0x8F) {
                if (yych <= 0x80) goto yy46;
                if (yych == 0x84) goto yy94;
                goto yy62;
              } else {
                if (yych <= 0xA0) {
                  if (yych <= 0x99) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xBA) goto yy46;
                  if (yych <= 0xBF) goto yy62;
                  goto yy46;
                }
              }
yy100:
              yych = *++sp;
              if (yych == 0xA9) goto yy62;
              goto yy46;
yy101:
              yych = *++sp;
              if (yych == 0x80) goto yy62;
              if (yych <= 0x9A) goto yy46;
              if (yych <= 0xA5) goto yy62;
              goto yy46;
yy102:
              yych = *++sp;
              if (yych <= 0xA6) {
                if (yych <= 0x7F) goto yy46;
                if (yych == 0x93) goto yy46;
                goto yy62;
              } else {
                if (yych <= 0xA8) {
                  if (yych <= 0xA7) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xA9) goto yy94;
                  if (yych <= 0xAB) goto yy62;
                  goto yy46;
                }
              }
yy103:
              yych = *++sp;
              if (yych <= 0xBD) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy104:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0x99) goto yy62;
              if (yych <= 0xAF) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy105:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0xA7) goto yy62;
              if (yych <= 0xAF) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy106:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy107:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x95) goto yy62;
              if (yych <= 0xAF) goto yy46;
              if (yych <= 0xBB) goto yy62;
              goto yy46;
yy108:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy109:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy110:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych == 0x9A) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy111:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xB3) goto yy62;
              goto yy46;
yy112:
              yych = *++sp;
              if (yych <= 0xB8) {
                if (yych <= 0xA4) goto yy46;
                if (yych <= 0xAA) goto yy62;
                goto yy46;
              } else {
                if (yych == 0xBD) goto yy46;
                if (yych <= 0xBF) goto yy62;
                goto yy46;
              }
yy113:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy114:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x8C) goto yy62;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0x99) goto yy62;
              goto yy46;
yy115:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy116:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy117:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy118:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy119:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych == 0x94) goto yy62;
                goto yy46;
              } else {
                if (yych == 0xB0) goto yy46;
                if (yych <= 0xBE) goto yy62;
                goto yy46;
              }
yy120:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x80) goto yy46;
                if (yych == 0x85) goto yy46;
                goto yy62;
              } else {
                if (yych <= 0xA7) {
                  if (yych <= 0x8B) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xA8) goto yy46;
                  if (yych <= 0xBF) goto yy62;
                  goto yy46;
                }
              }
yy121:
              yych = *++sp;
              if (yych <= 0x8E) {
                if (yych <= 0x8B) {
                  if (yych <= 0x7F) goto yy46;
                  goto yy62;
                } else {
                  if (yych == 0x8D) goto yy62;
                  goto yy46;
                }
              } else {
                if (yych <= 0x9E) {
                  if (yych <= 0x92) goto yy62;
                  if (yych <= 0x95) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xA0) goto yy46;
                  if (yych <= 0xB5) goto yy62;
                  goto yy46;
                }
              }
yy122:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy123:
              yych = *++sp;
              if (yych <= 0xA1) {
                if (yych <= 0x7F) goto yy46;
                if (yych == 0x8E) goto yy46;
                goto yy62;
              } else {
                if (yych <= 0xA3) {
                  if (yych <= 0xA2) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xA7) goto yy46;
                  if (yych <= 0xBF) goto yy62;
                  goto yy46;
                }
              }
yy124:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy125:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy126:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy127:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy128:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy129:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy130:
              yych = *++sp;
              if (yych <= 0x9B) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy131:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xA9) goto yy62;
              goto yy46;
yy132:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xA6) goto yy62;
              goto yy46;
yy133:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x8A) goto yy62;
              goto yy46;
yy134:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy135:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xA8) goto yy62;
              goto yy46;
yy136:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy137:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy138:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy139:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy140:
              yych = *++sp;
              switch (yych) {
              case 0x80:
              case 0x81:
              case 0x83:
              case 0x84:
              case 0x85:
              case 0x86:
              case 0x88:
              case 0x89:
              case 0x94:
              case 0x96:
              case 0x97:
              case 0x98:
              case 0x9E:
              case 0x9F:
              case 0xA0:
              case 0xA1:
              case 0xA2:
              case 0xA3:
              case 0xA5:
              case 0xA7:
              case 0xA9:
              case 0xAE:
              case 0xBA:
              case 0xBB:  goto yy62;
              default:  goto yy46;
              }
yy141:
              yych = *++sp;
              if (yych <= 0x89) {
                if (yych <= 0x7F) goto yy46;
                if (yych <= 0x84) goto yy62;
                goto yy46;
              } else {
                if (yych == 0x8E) goto yy46;
                if (yych <= 0x8F) goto yy62;
                goto yy46;
              }
yy142:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy143:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy144:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy145:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy146:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy147:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy148:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy149:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy150:
              yych = *++sp;
              if (yych <= 0x8B) {
                if (yych <= 0x7F) goto yy46;
                if (yych <= 0x8A) goto yy62;
                goto yy46;
              } else {
                if (yych <= 0x8C) goto yy62;
                if (yych <= 0x8F) goto yy46;
                if (yych <= 0xBF) goto yy62;
                goto yy46;
              }
yy151:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy152:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy153:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy154:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy155:
              yych = *++sp;
              if (yych <= 0x89) goto yy46;
              if (yych <= 0x8E) goto yy62;
              if (yych <= 0x9F) goto yy46;
              if (yych <= 0xB8) goto yy94;
              goto yy46;
yy156:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x9E) goto yy62;
              if (yych <= 0xB9) goto yy46;
              if (yych <= 0xBE) goto yy62;
              goto yy46;
yy157:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych == 0xAF) goto yy46;
              if (yych <= 0xB1) goto yy62;
              goto yy46;
yy158:
              yych = *++sp;
              if (yych == 0x85) goto yy62;
              if (yych <= 0xBD) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy159:
              yych = *++sp;
              if (yych <= 0x86) {
                if (yych <= 0x7F) goto yy46;
                if (yych <= 0x85) goto yy62;
                goto yy46;
              } else {
                if (yych == 0x8D) goto yy46;
                if (yych <= 0x98) goto yy62;
                goto yy46;
              }
yy160:
              yych = *++sp;
              if (yych <= 0xB4) {
                if (yych <= 0x99) {
                  if (yych <= 0x80) goto yy46;
                  if (yych <= 0x97) goto yy62;
                  goto yy46;
                } else {
                  if (yych <= 0x9F) goto yy62;
                  if (yych <= 0xB3) goto yy46;
                  goto yy62;
                }
              } else {
                if (yych <= 0xB7) {
                  if (yych == 0xB6) goto yy62;
                  goto yy46;
                } else {
                  if (yych == 0xB9) goto yy46;
                  if (yych <= 0xBD) goto yy62;
                  goto yy46;
                }
              }
yy161:
              yych = *++sp;
              if (yych == 0xB9) goto yy62;
              goto yy46;
yy162:
              yych = *++sp;
              if (yych <= 0xB0) goto yy46;
              if (yych <= 0xB2) goto yy62;
              goto yy46;
yy163:
              yych = *++sp;
              if (yych == 0xBF) goto yy62;
              goto yy46;
yy164:
              yych = *++sp;
              if (yych <= 0xB2) goto yy46;
              if (yych == 0xB9) goto yy94;
              if (yych <= 0xBA) goto yy62;
              goto yy46;
yy165:
              yych = *++sp;
              if (yych == 0xB0) goto yy62;
              goto yy46;
yy166:
              yych = *++sp;
              if (yych <= 0xB9) {
                if (yych <= 0xB1) goto yy46;
                if (yych <= 0xB3) goto yy94;
                goto yy46;
              } else {
                if (yych <= 0xBA) goto yy62;
                if (yych <= 0xBB) goto yy94;
                goto yy46;
              }
yy167:
              yych = *++sp;
              if (yych == 0x8F) goto yy62;
              if (yych <= 0x99) goto yy46;
              if (yych <= 0x9B) goto yy62;
              goto yy46;
yy168:
              yych = *++sp;
              if (yych == 0xB4) goto yy62;
              goto yy46;
yy169:
              yych = *++sp;
              if (yych <= 0xA3) goto yy46;
              if (yych <= 0xA5) goto yy62;
              if (yych == 0xB0) goto yy62;
              goto yy46;
yy170:
              yych = *++sp;
              if (yych <= 0xAF) goto yy46;
              if (yych <= 0xBE) goto yy62;
              goto yy46;
yy171:
              yych = *++sp;
              if (yych == 0xB1) goto yy94;
              goto yy46;
yy172:
              yych = *++sp;
              if (yych == 0xBF) goto yy94;
              goto yy46;
yy173:
              yych = *++sp;
              if (yych <= 0x8F) goto yy46;
              if (yych <= 0x99) goto yy62;
              goto yy46;
yy174:
              yych = *++sp;
              if (yych <= 0x99) goto yy46;
              if (yych <= 0xAA) goto yy62;
              if (yych <= 0xB3) goto yy46;
              if (yych <= 0xBC) goto yy62;
              goto yy46;
yy175:
              yych = *++sp;
              if (yych <= 0x9F) goto yy46;
              if (yych <= 0xA8) goto yy62;
              goto yy46;
yy176:
              yych = *++sp;
              if (yych <= 0x9D) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy177:
              yych = *++sp;
              if (yych == 0x80) goto yy62;
              if (yych <= 0x83) goto yy46;
              if (yych <= 0x85) goto yy62;
              goto yy46;
yy178:
              yych = *++sp;
              if (yych <= 0x9D) goto yy46;
              if (yych <= 0x9F) goto yy62;
              goto yy46;
yy179:
              yych = *++sp;
              if (yych == 0xBD) goto yy62;
              if (yych == 0xBF) goto yy62;
              goto yy46;
yy180:
              yych = *++sp;
              if (yych <= 0x9C) {
                if (yych <= 0x81) {
                  if (yych <= 0x7F) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0x8C) goto yy46;
                  if (yych <= 0x8F) goto yy62;
                  goto yy46;
                }
              } else {
                if (yych <= 0xAF) {
                  if (yych <= 0x9F) goto yy62;
                  if (yych <= 0xAC) goto yy46;
                  goto yy62;
                } else {
                  if (yych <= 0xBC) goto yy46;
                  if (yych <= 0xBE) goto yy62;
                  goto yy46;
                }
              }
yy181:
              yych = *++sp;
              if (yych <= 0x9A) goto yy46;
              if (yych <= 0x9C) goto yy62;
              goto yy46;
yy182:
              yych = *++sp;
              if (yych <= 0x97) {
                if (yych <= 0x93) goto yy46;
                if (yych <= 0x96) goto yy62;
                goto yy46;
              } else {
                if (yych <= 0x9A) goto yy62;
                if (yych <= 0x9B) goto yy94;
                goto yy46;
              }
yy183:
              yych = *++sp;
              if (yych <= 0xB4) goto yy46;
              if (yych <= 0xB6) goto yy62;
              goto yy46;
yy184:
              yych = *++sp;
              if (yych <= 0xAA) goto yy46;
              if (yych <= 0xAD) goto yy62;
              goto yy46;
yy185:
              yych = *++sp;
              if (yych <= 0xAC) goto yy46;
              if (yych <= 0xAE) goto yy62;
              goto yy46;
yy186:
              yych = *++sp;
              if (yych == 0x93) goto yy62;
              goto yy46;
yy187:
              yych = *++sp;
              if (yych <= 0xBA) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy188:
              yych = *++sp;
              if (yych <= 0xBD) goto yy46;
              if (yych <= 0xBF) goto yy62;
              goto yy46;
yy189:
              yych = *++sp;
              if (yych <= 0x9F) goto yy46;
              if (yych == 0xA7) goto yy46;
              if (yych <= 0xAD) goto yy62;
              goto yy46;
yy190:
              yych = *++sp;
              if (yych <= 0x9D) goto yy46;
              if (yych <= 0x9F) goto yy62;
              goto yy46;
yy191:
              yych = *++sp;
              if (yych == 0xBB) goto yy62;
              goto yy46;
yy192:
              yych = *++sp;
              if (yych <= 0x7F) goto yy46;
              if (yych <= 0x8A) goto yy62;
              goto yy46;
yy193:
              yych = *++sp;
              if (yych <= 0x89) goto yy46;
              if (yych <= 0x8F) goto yy62;
              goto yy46;
yy194:
              yych = *++sp;
              if (yych == 0x80) goto yy62;
              goto yy46;
yy195:
              ++sp;
              {
                                                   token.insert("NN","");
                                                   token.insert("$(","");
                                                   token.insert("$PARAGRAPH","");
                                                   return;
                                                 }
yy197:
              ++sp;
              {
                                                   token.insert("NN","");
                                                   token.insert("$(","");
                                                   token.insert("$PERCENT","");
                                                   return;
                                                 }
yy199:
              ++sp;
              { token.insert("$.",""); return; }
yy201:
              ++sp;
              { token.insert("$,",""); return; }
yy203:
              ++sp;
yy204:
              { token.insert("$.",""); return; }
yy205:
              ++sp;
              yych = *sp;
              if (yych <= '!') {
                if (yych <= 0x00) goto yy207;
                if (yych <= ' ') goto yy46;
                goto yy205;
              } else {
                if (yych == '?') goto yy205;
                goto yy46;
              }
yy207:
              yych = *++sp;
              goto yy204;
yy208:
              ++sp;
yy209:
              {
                                                   token.insert("$.","");
                                                   token.insert("$(","");
                                                   return;
                                                 }
yy210:
              ++sp;
              yych = *sp;
              if (yych <= '.') {
                if (yych <= 0x00) goto yy212;
                if (yych <= '-') goto yy46;
                goto yy210;
              } else {
                if (yych == ':') goto yy210;
                goto yy46;
              }
yy212:
              yych = *++sp;
              goto yy209;
yy213:
              ++sp;
              { token.insert("$.",""); return; }
yy215:
              ++sp;
              yych = *sp;
              if (yych <= '.') {
                if (yych <= 0x00) goto yy217;
                if (yych <= '-') goto yy46;
                goto yy215;
              } else {
                if (yych == ':') goto yy210;
                goto yy46;
              }
yy217:
              ++sp;
              yych = *sp;
              goto yy209;
            }

  }

} // namespace moot
